table 'Agents 365'
	lineageTag: 42005659-2cfe-4600-a91e-6c707a2318e9

	/// Most popular shared agent creator
	/// 👤 Top agent builder
	/// 💡 Recognize and support
	measure 'Most Popular Agent Creator (Shared - Agent Builder)' = ```
			
			VAR CreatorActiveUsers = 
			    ADDCOLUMNS(
			        SUMMARIZE(
			            FILTER('Agents 365', 'Agents 365'[Agent Type Combined] = "Agent Builder"),
			            'Agents 365'[Agent creator]
			        ),
			        "@TotalUsers", 
			            CALCULATE(
			                DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			                'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			                NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId])),
			                'Agents 365'[Agent Type Combined] = "Agent Builder"
			            )
			    )
			VAR MaxUsers = MAXX(CreatorActiveUsers, [@TotalUsers])
			VAR MostPopularCreator = 
			    FILTER(
			        CreatorActiveUsers,
			        [@TotalUsers] = MaxUsers
			    )
			RETURN
			    CONCATENATEX(MostPopularCreator, 'Agents 365'[Agent creator], ", ")
			```
		lineageTag: 08e8a2ef-be45-41e1-931b-3d76e434147c

	/// Percentage of users who return to use this agent multiple times (2+ sessions)
	measure 'Agent Return Rate' = ```
			VAR AgentName = SELECTEDVALUE('Agents 365'[Agent name])
			
			// Get all users and their session counts for this agent
			VAR UserSessions = 
			    SUMMARIZE(
			        FILTER(
			            ALL('Chat + Agent Interactions (Audit Logs)'),
			            'Chat + Agent Interactions (Audit Logs)'[AgentName] = AgentName
			        ),
			        'Chat + Agent Interactions (Audit Logs)'[Audit_UserId],
			        "SessionCount", DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId])
			    )
			
			// Count total unique users
			VAR TotalUsers = COUNTROWS(UserSessions)
			
			// Count users with 2+ sessions (return users)
			VAR ReturnUsers = 
			    COUNTROWS(
			        FILTER(UserSessions, [SessionCount] >= 2)
			    )
			
			RETURN
			    DIVIDE(ReturnUsers, TotalUsers, 0)
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 🚀 Frontier Firm
		lineageTag: 9c1b7c1a-c6c3-4fd3-ac05-e046052851d7

	/// Return rate for the agent in current filter context. % of users with 2+ sessions.
	measure 'Agent Return Rate (Table)' =
			
			VAR UserSessions =
			    ADDCOLUMNS(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        "@Sess", CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			        )
			    )
			VAR TotalUsers = COUNTROWS(UserSessions)
			VAR ReturnUsers = COUNTROWS(FILTER(UserSessions, [@Sess] >= 2)) + 0
			RETURN
			    IF(TotalUsers = 0, BLANK(), DIVIDE(ReturnUsers, TotalUsers, 0))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 🚀 Frontier Firm
		lineageTag: feaa2630-b1d9-4ef0-91a3-e36b2ae62632

	column 'Supported in'
		dataType: string
		lineageTag: 17b1002e-e0a0-4a36-ab86-bbe2cc5f824b
		summarizeBy: none
		sourceColumn: Supported in

		annotation SummarizationSetBy = Automatic

	column 'Date created'
		dataType: dateTime
		formatString: General Date
		lineageTag: bdb82158-56a0-4907-90fb-c8f37c6acce7
		summarizeBy: none
		sourceColumn: Date created

		annotation SummarizationSetBy = Automatic

	column 'Created in'
		dataType: string
		lineageTag: c208e589-f97e-42f3-b8fb-fbadfba361c8
		summarizeBy: none
		sourceColumn: Created in

		annotation SummarizationSetBy = Automatic

	column 'Last updated'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5e51001b-e68f-417e-85b2-167f18e703a8
		summarizeBy: none
		sourceColumn: Last updated

		annotation SummarizationSetBy = Automatic

	column 'Custom actions'
		dataType: string
		lineageTag: 9873df69-384c-4490-a896-9221c19c7e30
		summarizeBy: none
		sourceColumn: Custom actions

		annotation SummarizationSetBy = Automatic

	column 'Title ID'
		dataType: string
		lineageTag: 172b8d34-8796-4ca5-a2dd-3cb9bcde4c87
		summarizeBy: none
		sourceColumn: Title ID

		annotation SummarizationSetBy = Automatic

	column 'Can read OneDrive files'
		dataType: string
		lineageTag: 75c3aeca-daf8-43e9-a80d-28842e314b8e
		summarizeBy: none
		sourceColumn: Can read OneDrive files

		annotation SummarizationSetBy = Automatic

	column 'Can read Sharepoint sites and files'
		dataType: string
		lineageTag: 6a4bd3ca-5185-4ad6-9c1f-c1d62b8d6c5c
		summarizeBy: none
		sourceColumn: Can read Sharepoint sites and files

		annotation SummarizationSetBy = Automatic

	column 'Can extend to Graph connector'
		dataType: string
		lineageTag: 1e2686ed-ea80-4748-8fe5-e48e5fe14b31
		summarizeBy: none
		sourceColumn: Can extend to Graph connector

		annotation SummarizationSetBy = Automatic

	column 'Can generate images using user prompt'
		dataType: string
		lineageTag: 7f18151f-1f21-4bf4-9997-be8045ff0ba3
		summarizeBy: none
		sourceColumn: Can generate images using user prompt

		annotation SummarizationSetBy = Automatic

	column 'Can use code interpreter'
		dataType: string
		lineageTag: a28569bf-f02e-43ca-ac8d-de6f6fec9a5a
		summarizeBy: none
		sourceColumn: Can use code interpreter

		annotation SummarizationSetBy = Automatic

	column 'Contains uploaded files'
		dataType: string
		lineageTag: 5d3a1792-5339-4e32-b7b4-e69f9727ef43
		summarizeBy: none
		sourceColumn: Contains uploaded files

		annotation SummarizationSetBy = Automatic

	column 'Agent Type Combined' = ```
			
			IF(
			    'Agents 365'[Agent type (A365)] = "Shared" && 
			    'Agents 365'[Created in] = "Microsoft 365 Copilot Agent Builder",
			    "Agent Builder",
			    'Agents 365'[Agent type (A365)]
			)
			```
		lineageTag: dd221d12-3aef-458b-a221-7f6087c31d0c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Agent Last Activity Date' = ```
			VAR LastUsedDate = 
			    CALCULATE(
			        MAX('Chat + Agent Interactions (Audit Logs)'[Agent Last Used Date])
			    )
			VAR MaxDateInData = 
			    CALCULATE(
			        MAX('Chat + Agent Interactions (Audit Logs)'[CreationDate]),
			        ALL('Chat + Agent Interactions (Audit Logs)')
			    )
			VAR AgentCreatedDate = 'Agents 365'[Date created]
			VAR DaysSinceUsed = 
			    IF(
			        NOT(ISBLANK(LastUsedDate)),
			        DATEDIFF(LastUsedDate, MaxDateInData, DAY),
			        BLANK()
			    )
			VAR DaysSinceCreated = 
			    IF(
			        NOT(ISBLANK(AgentCreatedDate)),
			        DATEDIFF(AgentCreatedDate, MaxDateInData, DAY),
			        BLANK()
			    )
			RETURN
			    SWITCH(
			        TRUE(),
			        NOT(ISBLANK(DaysSinceUsed)) && DaysSinceUsed <= 7, "1. Active (Last 7 days)",
			        NOT(ISBLANK(DaysSinceUsed)) && DaysSinceUsed <= 30, "2. Recent (Last 30 days)",
			        NOT(ISBLANK(DaysSinceUsed)) && DaysSinceUsed <= 60, "3. Inactive (30-60 days)",
			        NOT(ISBLANK(DaysSinceUsed)) && DaysSinceUsed <= 90, "4. Dormant (60-90 days)",
			        NOT(ISBLANK(DaysSinceUsed)), "5. Redundant (90+ days)",
			        ISBLANK(LastUsedDate) && DaysSinceCreated <= 14, "6. New (Not Yet Used)",
			        ISBLANK(LastUsedDate) && DaysSinceCreated <= 90, "7. Never Used (Recent)",
			        ISBLANK(LastUsedDate), "8. Never Used (Stale)",
			        "Unknown"
			    )
			```
		lineageTag: 596582bc-72c6-4755-bdad-067976ea0c39
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Agent Review' = ```
			VAR Users = 'Agents 365'[Total Users]
			VAR InactivityStatus = 'Agents 365'[Agent Last Activity Date]
			VAR AgentType = 'Agents 365'[Agent Type Combined]
			VAR _TotalUsers = 'Agents 365'[Total Users]
			VAR _OrgCount = 'Agents 365'[Org Count]
			
			// Type-specific user thresholds
			VAR LowUserThreshold = 
			    SWITCH(
			        AgentType,
			        "FirstParty", 20,
			        "Agent Builder", 5,
			        10
			    )
			
			VAR MinUserThreshold = 
			    SWITCH(
			        AgentType,
			        "FirstParty", 10,
			        "Agent Builder", 2,
			        5
			    )
			
			// High Impact thresholds (uses pre-calculated columns - fast)
			VAR HighImpactUsers = 
			    SWITCH(
			        AgentType,
			        "FirstParty", 100,
			        "Agent Builder", 30,
			        50
			    )
			VAR HighImpactOrgs = 
			    SWITCH(
			        AgentType,
			        "FirstParty", 10,
			        "Agent Builder", 3,
			        5
			    )
			
			RETURN
			    SWITCH(
			        TRUE(),
			        
			        // New agents - give them time
			        InactivityStatus = "6. New (Not Yet Used)",
			            "🆕 New",
			        
			        // Never used (not new) - created but no usage
			        InactivityStatus IN {"7. Never Used (Recent)", "8. Never Used (Stale)"},
			            "❌ Never Used",
			        
			        // Active/Recent - split into High Impact vs Keep
			        InactivityStatus IN {"1. Active (Last 7 days)", "2. Recent (Last 30 days)"}, 
			            IF(
			                _TotalUsers >= HighImpactUsers && _OrgCount >= HighImpactOrgs,
			                "🔥 High Impact",
			                "✅ Keep"
			            ),
			        
			        // 30-60 days inactive + low users = Review
			        InactivityStatus = "3. Inactive (30-60 days)" && Users < LowUserThreshold,
			            "⚠️ Review",
			        
			        // 60-90 days Dormant
			        InactivityStatus = "4. Dormant (60-90 days)",
			            SWITCH(
			                TRUE(),
			                Users < MinUserThreshold, "💤 Dormant",
			                Users < LowUserThreshold, "⚠️ Review",
			                "✅ Keep"
			            ),
			        
			        // 90+ days Redundant
			        InactivityStatus = "5. Redundant (90+ days)",
			            IF(Users < LowUserThreshold, "💤 Dormant", "⚠️ Review"),
			        
			        // Default
			        "✅ Keep"
			    )
			```
		lineageTag: 5da9ee56-b586-4e58-a717-f5d34edd6eee
		summarizeBy: none
		sortByColumn: 'Agent Review Sort'

		annotation SummarizationSetBy = Automatic

	column 'Agent Features' = ```
			
			VAR SupportedIn = 'Agents 365'[Supported in]
			
			// Platform icons + labels
			VAR HasTeams = IF(SEARCH("Teams", SupportedIn, 1, 0) > 0, "💬 in Teams ", "")
			VAR HasOutlook = IF(SEARCH("Outlook", SupportedIn, 1, 0) > 0, "📧 in Outlook ", "")
			VAR HasOffice = IF(SEARCH("Office", SupportedIn, 1, 0) > 0, "📄 in Office ", "")
			
			VAR Platforms = TRIM(HasTeams & HasOutlook & HasOffice)
			
			// Capability icons + labels (core data sources only)
			VAR SPO = IF('Agents 365'[Can read Sharepoint sites and files] = "Yes", "📁 SharePoint ", "")
			VAR OneDrive = IF('Agents 365'[Can read OneDrive files] = "Yes", "☁️ OneDrive ", "")
			VAR Graph = IF('Agents 365'[Can extend to Graph connector] = "Yes", "🔌 Graph ", "")
			VAR Files = IF('Agents 365'[Contains uploaded files] = "Yes", "📎 Files ", "")
			
			VAR Capabilities = TRIM(SPO & OneDrive & Graph & Files)
			
			// Combine with separator
			VAR Combined = 
			    IF(
			        Platforms <> "" && Capabilities <> "",
			        Platforms & " | " & Capabilities,
			        Platforms & Capabilities
			    )
			
			RETURN
			    IF(Combined = "", BLANK(), Combined)
			```
		lineageTag: 7f224cd3-5ced-48b6-9d60-9abe8fbd5da8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Agent name'
		dataType: string
		lineageTag: fca0dee6-c592-42fa-929a-fa98a557b60c
		summarizeBy: none
		sourceColumn: Agent name

		annotation SummarizationSetBy = Automatic

	column 'Agent creator'
		dataType: string
		lineageTag: 37938f22-86d7-47de-aae8-927740fd0253
		summarizeBy: none
		sourceColumn: Agent creator

		annotation SummarizationSetBy = Automatic

	column 'Agent type (A365)'
		dataType: string
		lineageTag: 01e8516f-9c48-448a-9cb3-d2ce43e68e81
		summarizeBy: none
		sourceColumn: Agent type (A365)

		annotation SummarizationSetBy = Automatic

	column 'Agent description'
		dataType: string
		lineageTag: 8c302435-6639-4b6d-8e6d-0f36b57f9ae8
		summarizeBy: none
		sourceColumn: Agent description

		annotation SummarizationSetBy = Automatic

	/// Pre-calculated total users for this agent
	column 'Total Users' =
			VAR AgentName = 'Agents 365'[Agent name]
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        'Chat + Agent Interactions (Audit Logs)'[AgentName] = AgentName
			    )
		dataType: int64
		lineageTag: 576215bd-ee2b-44bd-978d-03605a14cffb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Pre-calculated organization spread
	column 'Org Count' = ```
			VAR AgentName = 'Agents 365'[Agent name]
			VAR AgentUsers = 
			    CALCULATETABLE(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        'Chat + Agent Interactions (Audit Logs)'[AgentName] = AgentName
			    )
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Org Data'[Organization]),
			        FILTER(
			            ALL('Chat + Agent Org Data'),
			            'Chat + Agent Org Data'[PersonId] IN AgentUsers
			        )
			    )
			```
		dataType: int64
		lineageTag: e7eb4d3b-876a-4bdc-987c-9838379290d1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// TRUE if this is the primary version of the agent (most users when duplicates exist)
	column 'Is Primary Agent' = ```
			VAR CurrentAgentName = 'Agents 365'[Agent name]
			VAR CurrentUsers = 'Agents 365'[Total Users]
			VAR CurrentTitleID = 'Agents 365'[Title ID]
			
			-- Find the max users for this agent name
			VAR MaxUsersForName = 
			    CALCULATE(
			        MAX('Agents 365'[Total Users]),
			        FILTER(
			            ALL('Agents 365'),
			            'Agents 365'[Agent name] = CurrentAgentName
			        )
			    )
			
			-- If there are ties, use the Title ID as tiebreaker (first alphabetically)
			VAR TitleIDWithMaxUsers = 
			    CALCULATE(
			        MIN('Agents 365'[Title ID]),
			        FILTER(
			            ALL('Agents 365'),
			            'Agents 365'[Agent name] = CurrentAgentName &&
			            'Agents 365'[Total Users] = MaxUsersForName
			        )
			    )
			
			RETURN
			    CurrentTitleID = TitleIDWithMaxUsers
			```
		dataType: boolean
		lineageTag: 9fa1db4e-af92-4f47-8944-46e07c211e73
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Sort order for Agent Review column
	column 'Agent Review Sort' = ```
			VAR InactivityStatus = 'Agents 365'[Agent Last Activity Date]
			VAR AgentType = 'Agents 365'[Agent Type Combined]
			VAR _TotalUsers = 'Agents 365'[Total Users]
			VAR _OrgCount = 'Agents 365'[Org Count]
			VAR Users = 'Agents 365'[Total Users]
			
			VAR LowUserThreshold = 
			    SWITCH(AgentType, "FirstParty", 20, "Agent Builder", 5, 10)
			VAR MinUserThreshold = 
			    SWITCH(AgentType, "FirstParty", 10, "Agent Builder", 2, 5)
			VAR HighImpactUsers = 
			    SWITCH(AgentType, "FirstParty", 100, "Agent Builder", 30, 50)
			VAR HighImpactOrgs = 
			    SWITCH(AgentType, "FirstParty", 10, "Agent Builder", 3, 5)
			
			RETURN
			    SWITCH(
			        TRUE(),
			        InactivityStatus = "6. New (Not Yet Used)", 3,
			        InactivityStatus IN {"7. Never Used (Recent)", "8. Never Used (Stale)"}, 6,
			        InactivityStatus IN {"1. Active (Last 7 days)", "2. Recent (Last 30 days)"},
			            IF(_TotalUsers >= HighImpactUsers && _OrgCount >= HighImpactOrgs, 1, 2),
			        InactivityStatus = "3. Inactive (30-60 days)" && Users < LowUserThreshold, 4,
			        InactivityStatus = "4. Dormant (60-90 days)",
			            SWITCH(TRUE(), Users < MinUserThreshold, 5, Users < LowUserThreshold, 4, 2),
			        InactivityStatus = "5. Redundant (90+ days)",
			            IF(Users < LowUserThreshold, 5, 4),
			        2
			    )
			```
		dataType: int64
		isHidden
		lineageTag: 4250a59a-df9f-4f33-90bf-350885ae9c9c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Pre-computed return rate: % of users with 2+ sessions. Calculated at refresh time for performance.
	column 'Return Rate Value' =
			
			VAR TotalUsers =
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			    )
			VAR ReturnUsers =
			    COUNTROWS(
			        FILTER(
			            ADDCOLUMNS(
			                CALCULATETABLE(
			                    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			                    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			                ),
			                "@Sess", CALCULATE(
			                    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			                    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			                )
			            ),
			            [@Sess] >= 2
			        )
			    ) + 0
			RETURN
			    IF(TotalUsers = 0, BLANK(), DIVIDE(ReturnUsers, TotalUsers, 0))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c976c286-3469-40d2-a344-27990eb84e60
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Categorized return rate: High (≥50%), Medium (20-49%), Low (<20%). Pre-computed at refresh.
	column 'Return Rate Category' =
			
			VAR Rate = 'Agents 365'[Return Rate Value]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Rate), "No Usage",
			        Rate >= 0.50, "High",
			        Rate >= 0.20, "Medium",
			        "Low"
			    )
		lineageTag: 48a35637-aa39-474f-848e-13ae8b3fef81
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 8bdcc950-d847-4932-a1ba-045ae5edc1ef
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Availability
		dataType: string
		lineageTag: 2b0f99c1-b719-47ff-8d15-866436d02ef7
		summarizeBy: none
		sourceColumn: Availability

		annotation SummarizationSetBy = Automatic

	column 'Agent creator ID'
		dataType: string
		lineageTag: 72d62676-50fd-470d-9af3-aab49ff0821c
		summarizeBy: none
		sourceColumn: Agent creator ID

		annotation SummarizationSetBy = Automatic

	column Sensitivity
		dataType: string
		lineageTag: 86c2a0ba-57fe-46e5-b132-386a5f55ec8d
		summarizeBy: none
		sourceColumn: Sensitivity

		annotation SummarizationSetBy = Automatic

	column 'Can read OneDrive and Sharepoint items'
		dataType: string
		lineageTag: 0f5714fc-3bb9-4da6-8fd8-f9d910b19adf
		summarizeBy: none
		sourceColumn: Can read OneDrive and Sharepoint items

		annotation SummarizationSetBy = Automatic

	column 'OneDrive and Sharepoint items'
		dataType: string
		lineageTag: 4f5f9c73-1312-4abf-af4a-957a6a1e5eba
		summarizeBy: none
		sourceColumn: OneDrive and Sharepoint items

		annotation SummarizationSetBy = Automatic

	column 'OneDrive files'
		dataType: string
		lineageTag: f4cf86b7-87c2-49a3-95f1-d7cd11ccd063
		summarizeBy: none
		sourceColumn: OneDrive files

		annotation SummarizationSetBy = Automatic

	column 'OneDrive sites'
		dataType: string
		lineageTag: 868ef260-5081-40b4-a5be-bf8e6a9a506e
		summarizeBy: none
		sourceColumn: OneDrive sites

		annotation SummarizationSetBy = Automatic

	column 'Sharepoint files'
		dataType: string
		lineageTag: 54b8a589-1277-4ed7-a039-83d014d662c5
		summarizeBy: none
		sourceColumn: Sharepoint files

		annotation SummarizationSetBy = Automatic

	column 'Sharepoint sites'
		dataType: string
		lineageTag: 85e683f7-8ba5-4c60-a185-2d234700e1d5
		summarizeBy: none
		sourceColumn: Sharepoint sites

		annotation SummarizationSetBy = Automatic

	column 'Graph connector details'
		dataType: string
		lineageTag: d130e113-a955-4cfe-a127-07626c13619d
		summarizeBy: none
		sourceColumn: Graph connector details

		annotation SummarizationSetBy = Automatic

	column 'Uploaded files'
		dataType: string
		lineageTag: daad18e8-f8d0-4862-89c1-8a67e6934e05
		summarizeBy: none
		sourceColumn: Uploaded files

		annotation SummarizationSetBy = Automatic

	column 'Is Published' =
			-- TRUE when admin publication status is Available, OR when Status is blank
			-- (older exports don't carry Status — treat as published rather than hide everything).
			IF(
			    ISBLANK('Agents 365'[Status]) || 'Agents 365'[Status] = "",
			    TRUE(),
			    'Agents 365'[Status] = "Available"
			)
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cf02b2b2-2345-5ff6-a987-101122334455
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: cf7c8178-e119-4f30-9fd6-e1d7ca01fa78
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition 'Agents 365' = m
		mode: import
		source = ```
				let
				    FilePath = #"Agent 365",
				
				    // List the column names and types as in your table output after all transforms
				    EmptyTable = #table(
				        {
				            "Agent name", "Supported in", "Date created", "Agent creator", "Agent type (A365)", 
				            "Version", "Availability", "Agent creator ID", "Agent description", "Created in", 
				            "Last updated", "Custom actions", "Title ID", "Sensitivity", 
				            "Can read OneDrive and Sharepoint items", "OneDrive and Sharepoint items", 
				            "Can read OneDrive files", "OneDrive files", "OneDrive sites",
				            "Can read Sharepoint sites and files", "Sharepoint files", "Sharepoint sites",
				            "Can extend to Graph connector", "Graph connector details", 
				            "Can generate images using user prompt", "Can use code interpreter", 
				            "Contains uploaded files", "Uploaded files"
				        },
				        {}  // No rows
				    ),
				
				    Output =
				        if FilePath <> null and Text.Trim(FilePath) <> "" then
				            let
				                // SharePoint URL only — local paths are deliberately not supported on this variant.
				                Source = Csv.Document(Web.Contents(FilePath), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				                #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				
				                // Detect column name variants (old vs new format)
				                cols = Table.ColumnNames(#"Promoted Headers"),
				                nameCol = if List.Contains(cols, "Agent name") then "Agent name" else if List.Contains(cols, "Name") then "Name" else "Name",
				                creatorCol = if List.Contains(cols, "Agent creator") then "Agent creator" else if List.Contains(cols, "Publisher") then "Publisher" else if List.Contains(cols, "Developer Name") then "Developer Name" else "Agent creator",
				                typeCol = if List.Contains(cols, "Agent type (A365)") then "Agent type (A365)" else if List.Contains(cols, "Publisher Type") then "Publisher Type" else if List.Contains(cols, "Type") then "Type" else "Agent type (A365)",
				                creatorIdCol = if List.Contains(cols, "Agent creator ID") then "Agent creator ID" else if List.Contains(cols, "Owner") then "Owner" else if List.Contains(cols, "Created by") then "Created by" else "Agent creator ID",
				                descCol = if List.Contains(cols, "Agent description") then "Agent description" else if List.Contains(cols, "Description") then "Description" else "Description",
				                lastUpdatedCol = if List.Contains(cols, "Last updated") then "Last updated" else if List.Contains(cols, "Last Modified") then "Last Modified" else "Last updated",
				                platformCol = if List.Contains(cols, "Created in") then "Created in" else if List.Contains(cols, "Platform") then "Platform" else "Created in",
				
				                // Rename to canonical names
				                #"Normalized Columns" = Table.RenameColumns(
				                    #"Promoted Headers",
				                    List.Combine({
				                        if nameCol <> "Agent name" then {{nameCol, "Agent name"}} else {},
				                        if creatorCol <> "Agent creator" then {{creatorCol, "Agent creator"}} else {},
				                        if typeCol <> "Agent type (A365)" then {{typeCol, "Agent type (A365)"}} else {},
				                        if creatorIdCol <> "Agent creator ID" then {{creatorIdCol, "Agent creator ID"}} else {},
				                        if descCol <> "Agent description" then {{descCol, "Agent description"}} else {},
				                        if lastUpdatedCol <> "Last updated" then {{lastUpdatedCol, "Last updated"}} else {},
				                        if platformCol <> "Created in" then {{platformCol, "Created in"}} else {}
				                    }),
				                    MissingField.Ignore
				                ),
				
				                // Add "Last updated" if missing (new format drops it)
				                #"With Last Updated" = if List.Contains(Table.ColumnNames(#"Normalized Columns"), "Last updated") then #"Normalized Columns" else Table.AddColumn(#"Normalized Columns", "Last updated", each null, type datetime),
				                #"With Supported In" = if List.Contains(Table.ColumnNames(#"With Last Updated"), "Supported in") then #"With Last Updated" else Table.AddColumn(#"With Last Updated", "Supported in", each null, type text),
				                #"With Availability" = if List.Contains(Table.ColumnNames(#"With Supported In"), "Availability") then #"With Supported In" else Table.AddColumn(#"With Supported In", "Availability", each null, type text),
				                #"With Created In" = if List.Contains(Table.ColumnNames(#"With Availability"), "Created in") then #"With Availability" else Table.AddColumn(#"With Availability", "Created in", each null, type text),
				                // Status column — only present in the 2026-04-24+ export. Inject null for older formats
				                // so downstream calc columns (Is Published) work without errors on legacy data.
				                #"With Status" = if List.Contains(Table.ColumnNames(#"With Created In"), "Status") then #"With Created In" else Table.AddColumn(#"With Created In", "Status", each null, type text),
				
				                #"Changed Type" = Table.TransformColumnTypes(#"With Status",{{"Agent name", type text}, {"Supported in", type text}, {"Date created", type datetime}, {"Agent creator", type text}, {"Agent type (A365)", type text}, {"Version", type text}, {"Availability", type text}, {"Agent creator ID", type text}, {"Agent description", type text}, {"Created in", type text}, {"Last updated", type datetime}, {"Custom actions", type text}, {"Title ID", type text}, {"Sensitivity", type text}, {"Can read OneDrive and Sharepoint items", type text}, {"OneDrive and Sharepoint items", type text}, {"Can read OneDrive files", type text}, {"OneDrive files", type text}, {"OneDrive sites", type text}, {"Can read Sharepoint sites and files", type text}, {"Sharepoint files", type text}, {"Sharepoint sites", type text}, {"Can extend to Graph connector", type text}, {"Graph connector details", type text}, {"Can generate images using user prompt", type text}, {"Can use code interpreter", type text}, {"Contains uploaded files", type text}, {"Uploaded files", type text}, {"Status", type text}})
				            in
				                #"Changed Type"
				        else
				            EmptyTable
				in
				    Output
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

