table 'Augmented Skills Map'
	lineageTag: ff080001-0001-0001-0001-000000000001

	column Behavior
		dataType: string
		lineageTag: ff080001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: Behavior

		annotation SummarizationSetBy = Automatic

	column 'Augmented Skill'
		dataType: string
		lineageTag: ff080001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Augmented Skill

		annotation SummarizationSetBy = Automatic

	column 'Skill Category'
		dataType: string
		lineageTag: 98962703-b544-4e37-9b2c-4686653b668d
		summarizeBy: none
		sourceColumn: Skill Category

		annotation SummarizationSetBy = Automatic

	column 'Skill Description'
		dataType: string
		lineageTag: 7db7c502-7672-4dbb-846c-bc19be37a090
		summarizeBy: none
		sourceColumn: Skill Description

		annotation SummarizationSetBy = Automatic

	column 'Professional Equivalent'
		dataType: string
		lineageTag: 4ac63fc8-70ac-418f-bb69-b848f7ae49ff
		summarizeBy: none
		sourceColumn: Professional Equivalent

		annotation SummarizationSetBy = Automatic

	partition 'Augmented Skills Map' = m
		mode: import
		source =
				let
				    Source = #table(
				        {"Behavior", "Augmented Skill", "Skill Category", "Skill Description", "Professional Equivalent"},
				        {
				            {"Email Triage", "Inbox Management", "Productivity", "Prioritising and filtering high-volume email", "Executive Assistant"},
				            {"Email Thread Summary", "Comprehension & Synthesis", "Analysis", "Distilling multi-message threads into key points", "Analyst"},
				            {"Email Summarising", "Comprehension & Synthesis", "Analysis", "Extracting key points from email content", "Analyst"},
				            {"Email Drafting", "Business Writing", "Communication", "Composing professional correspondence", "Communications Specialist"},
				            {"Meeting Prep", "Meeting Intelligence", "Productivity", "Synthesising agendas, notes, and context before meetings", "Chief of Staff"},
				            {"Video Summarising", "Video Intelligence", "Analysis", "Extracting key moments and decisions from recordings", "Notetaker / Analyst"},
				            {"Document Summarising", "Research & Synthesis", "Analysis", "Distilling long documents into executive summaries", "Research Analyst"},
				            {"Presentation Summarising", "Research & Synthesis", "Analysis", "Extracting key messages from slide decks", "Strategy Analyst"},
				            {"Document Drafting", "Business Writing", "Communication", "Creating reports, proposals, and documentation", "Technical Writer"},
				            {"Presentation Creation", "Visual Communication", "Design", "Building slide decks and visual narratives", "Presentation Designer"},
				            {"Web Searching", "Research", "Analysis", "Market research, fact-checking, competitive intelligence", "Research Analyst"},
				            {"Enterprise Searching", "Knowledge Management", "Analysis", "Finding internal documents and institutional knowledge", "Knowledge Manager"},
				            {"PDF Analysis", "Document Review", "Legal / Compliance", "Contract review, report analysis, compliance checking", "Legal Analyst"},
				            {"SharePoint Access", "Knowledge Management", "Analysis", "Navigating shared content and team resources", "Information Architect"},
				            {"File Retrieval", "Research", "Analysis", "Cross-referencing documents and gathering context", "Research Assistant"},
				            {"Data Querying", "Data Analysis", "Data & Analytics", "Building reports and answering data questions", "Data Analyst"},
				            {"Spreadsheet Analysis", "Financial Analysis", "Data & Analytics", "Financial modelling, trend analysis, data validation", "Financial Analyst"},
				            {"Teams Messaging", "Business Writing", "Communication", "Drafting coordination messages and status updates", "Communications Coordinator"},
				            {"Meeting Scheduling", "Calendar Management", "Productivity", "Finding availability across teams", "Executive Assistant"},
				            {"Code Writing", "Software Development", "Engineering", "Feature development, scripting, automation", "Software Developer"},
				            {"Code Analysis", "Code Review", "Engineering", "Debugging, code comprehension, quality review", "Senior Developer"},
				            {"Code Analysis (URL)", "Technical Research", "Engineering", "Referencing coding documentation and resources", "Developer"},
				            {"Image Generation", "Graphic Design", "Design", "Creating marketing visuals, social content, presentations", "Graphic Designer"},
				            {"Image/Media Analysis", "Accessibility & Cataloguing", "Design", "Alt-text generation, content tagging, media review", "Content Cataloguer"},
				            {"Image / Media Analysis", "Accessibility & Cataloguing", "Design", "Alt-text generation, content tagging, media review", "Content Cataloguer"},
				            {"People Lookup", "Org Navigation", "People & Culture", "Finding experts, understanding team structures", "HR Business Partner"},
				            {"Workflow Execution", "Process Automation", "Operations", "Automating approvals, notifications, data flows", "Process Engineer"},
				            {"Task Management", "Project Management", "Operations", "Sprint planning, task tracking, coordination", "Project Manager"},
				            {"Real-time Collaboration", "Facilitation", "Collaboration", "Brainstorming, shared editing, team ideation", "Workshop Facilitator"},
				            {"Note Taking", "Documentation", "Productivity", "Meeting notes and knowledge capture", "Notetaker"},
				            {"Form/Survey Work", "Survey Design", "Research", "Building feedback forms, quizzes, surveys", "Market Researcher"},
				            {"Agent: Coaching", "Learning & Development", "People & Culture", "Writing coaching, career guidance, skill building", "L&D Specialist"},
				            {"Agent: Coaching (URL)", "Self-Directed Learning", "People & Culture", "Consuming learning platform content", "Training Coordinator"},
				            {"Agent: Sales & Customer", "Sales Intelligence", "Revenue", "Customer insights, deal support, CRM queries", "Sales Operations Analyst"},
				            {"Agent: IT & Service Desk", "IT Support", "Technology", "Troubleshooting, ticket triage, knowledge base queries", "IT Support Analyst"},
				            {"Agent: Compliance & Policy", "Regulatory Knowledge", "Legal / Compliance", "Policy lookup, compliance checking, risk assessment", "Compliance Analyst"},
				            {"Sensitive Content Interaction", "Data Classification", "Legal / Compliance", "Working with classified or protected content", "Information Security Analyst"},
				            {"Agent: Research & Analysis", "Strategic Research", "Analysis", "Market research, competitive analysis, trend spotting", "Strategy Consultant"},
				            {"Agent: Content Generation", "Content Creation", "Communication", "Drafting, summarising, translating content", "Content Strategist"},
				            {"Agent: Data & Reporting", "BI & Reporting", "Data & Analytics", "Building reports, dashboards, KPI tracking", "BI Developer"},
				            {"Agent: Knowledge Base", "Knowledge Retrieval", "Operations", "FAQ resolution, process guidance", "Knowledge Manager"},
				            {"Agent: HR & People", "HR Operations", "People & Culture", "Job descriptions, screening, onboarding", "HR Coordinator"},
				            {"Agent: Ideation & Creative", "Creative Strategy", "Design", "Brainstorming, design concepts, creative briefs", "Creative Director"},
				            {"Agent: General Purpose", "General Assistance", "Productivity", "Unclassified agent interactions", "Virtual Assistant"},
				            {"Domain-Specific Agent", "Domain Expertise", "Specialist", "Function-specific specialist support", "Subject Matter Expert"},
				            {"Cross-Org Agent", "Cross-Functional Support", "Collaboration", "Platform agent across multiple functions", "Business Analyst"},
				            {"M365 Chat Q&A", "Quick Research", "Productivity", "Ad-hoc questions and lookups", "Research Assistant"},
				            {"Teams Q&A", "Quick Research", "Productivity", "Ad-hoc questions in Teams", "Research Assistant"},
				            {"Browser Q&A", "Quick Research", "Productivity", "Ad-hoc questions in browser", "Research Assistant"},
				            {"General Q&A", "Quick Research", "Productivity", "General purpose questions", "Research Assistant"},
				            {"General Chat", "Quick Research", "Productivity", "General AI chat interactions", "Research Assistant"},
													// Bridge entries for Behavior_Enriched_Full variants emitted by Audit Logs DAX
													{"Spreadsheet Review", "Data Validation", "Data & Analytics", "Reviewing spreadsheets, validating numbers, light analysis", "Business Analyst"},
													{"Excel Assistance", "Spreadsheet Productivity", "Data & Analytics", "Excel-native AI help for formulas, formatting, ad-hoc analysis", "Data Analyst"},
													{"Form / Survey Work", "Survey Design", "Research", "Building feedback forms, quizzes, surveys (spaces variant)", "Market Researcher"}
				        }
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {
				        {"Behavior", type text},
				        {"Augmented Skill", type text},
				        {"Skill Category", type text},
				        {"Skill Description", type text},
				        {"Professional Equivalent", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

