table 'Behavior Value Map'
	lineageTag: ff050001-0001-0001-0001-000000000001

	column Signal
		dataType: string
		lineageTag: ff050001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: Signal

		annotation SummarizationSetBy = Automatic

	column Behavior
		dataType: string
		lineageTag: ff050001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Behavior

		annotation SummarizationSetBy = Automatic

	column 'Use Case'
		dataType: string
		lineageTag: ff050001-0001-0001-0001-000000000004
		summarizeBy: none
		sourceColumn: Use Case

		annotation SummarizationSetBy = Automatic

	column 'Value Outcome'
		dataType: string
		lineageTag: ff050001-0001-0001-0001-000000000005
		summarizeBy: none
		sourceColumn: Value Outcome

		annotation SummarizationSetBy = Automatic

	column 'Stage Typical'
		dataType: string
		lineageTag: f74b457f-8453-48cf-99d0-452297d5da66
		summarizeBy: none
		sourceColumn: Stage Typical

		annotation SummarizationSetBy = Automatic

	column 'Indicative Org Metric'
		dataType: string
		lineageTag: 63742646-e5f6-47bc-aaa5-adeaef6d9b7c
		summarizeBy: none
		sourceColumn: Indicative Org Metric

		annotation SummarizationSetBy = Automatic

	partition 'Behavior Value Map' = m
		mode: import
		source =
				let
				    Source = #table(
				        {"Signal", "Behavior", "Use Case", "Value Outcome", "Stage Typical", "Indicative Org Metric"},
				        {
				            // TIME SAVED (EMAIL)
				            {"Outlook + 5+ EmailMessages + Read", "Email Triage", "Bulk inbox scanning, catching up after leave", "Time Saved (Email)", "Developing", "Survey: mins saved/day on email. Benchmark: 3 min per triage session"},
				            {"Outlook + 1 EmailMessage + Read", "Email Thread Summary", "Summarising a specific email conversation", "Time Saved (Email)", "Developing", "Survey: mins saved/day on email. Benchmark: 2 min per thread summary"},
				            // TIME SAVED (MEETINGS)
				            {"Resource=Event/TeamsMeeting + Read", "Meeting Prep", "Reviewing agendas, catching up on missed meetings", "Time Saved (Meetings)", "Proficient", "Missed meeting catch-ups saved. Benchmark: 15 min per meeting prep"},
				            {"AppHost=Stream + mp4/StreamVideo", "Video Summarising", "Meeting recordings, training video recaps", "Time Saved (Meetings)", "Proficient", "Video watch time saved. Benchmark: 20 min per video summary"},
				            // TIME SAVED (DOCUMENTS)
				            {"AppHost=Word + docx + Read", "Document Summarising", "Executive summaries, long doc digests, research synthesis", "Time Saved (Documents)", "Developing", "Docs read per user. Benchmark: 10 min saved per doc summary"},
				            {"AppHost=PowerPoint + pptx + Read", "Presentation Summarising", "Deck reviews, extracting key points", "Time Saved (Documents)", "Developing", "Decks reviewed per user. Benchmark: 8 min saved per PPT summary"},
				            // CONTENT CREATION
				            {"Outlook + Send/Draft actions", "Email Drafting", "Composing replies, cold outreach, formal correspondence", "Content Output", "Proficient", "Emails drafted via AI per user/week. Before/after comparison"},
				            {"AppHost=Word + Post/Write/Create", "Document Drafting", "Reports, proposals, briefs, documentation", "Content Output", "Proficient", "Docs published per user/month (SharePoint analytics)"},
				            {"AppHost=PowerPoint + Post/Write/Create", "Presentation Creation", "Slide decks, pitch materials, training content", "Content Output", "Proficient", "Decks created per user/month"},
				            // FASTER INFORMATION FINDING
				            {"Plugin=BingWebSearch + WebSearchQuery", "Web Searching", "Market research, fact-checking, competitive analysis", "Search Time Saved", "Beginner", "Survey: time to find info (1-5 scale). Search sessions per user"},
				            {"Plugin=EnterpriseSearch + aspx/ListItem", "Enterprise Searching", "Finding internal docs, policy lookup, knowledge retrieval", "Search Time Saved", "Proficient", "Internal search sessions. Reduction in 'can''t find' support tickets"},
				            {"Resource=pdf + Read", "PDF Analysis", "Contract review, report analysis, compliance checking", "Search Time Saved", "Proficient", "PDFs analysed per user/month"},
				            {"AppHost=SharePoint", "SharePoint Access", "Site browsing, file discovery, team content", "Search Time Saved", "Developing", "SharePoint AI sessions vs direct visits"},
				            {"Resource=docx/pptx + Read (not native app)", "File Retrieval", "Cross-referencing documents, gathering context", "Search Time Saved", "Developing", "Files retrieved per session (research depth)"},
				            // DATA-DRIVEN DECISIONS
				            {"AppHost=Excel + ExecuteDatasetQuery", "Data Querying", "Building reports, answering data questions, KPI tracking", "Data-Driven Decisions", "Proficient", "Queries per user/week. Reports generated (Excel/PBI usage)"},
				            {"Resource=xlsx/csv/xlsm + Read", "Spreadsheet Analysis", "Financial analysis, data validation, trend spotting", "Data-Driven Decisions", "Proficient", "Spreadsheets analysed. Data-cited decisions (business review audit)"},
				            // BETTER COMMUNICATION
				            {"TeamsMessage/TeamsChat + Post/CreateChat", "Teams Messaging", "Team coordination, quick decisions, status updates", "Communication Time Saved", "Developing", "Teams AI sessions per user. Response time improvement (Viva Insights)"},
				            {"Action=mcp_MeetingManagement", "Meeting Scheduling", "Calendar management, finding availability", "Communication Time Saved", "Proficient", "Meetings scheduled via AI. Time saved on scheduling (survey)"},
				            // SKILLS DEVELOPMENT (coaching agents)
				            {"Agent: coach/mentor/learning/writing/prompt", "Agent: Coaching", "Writing coaching, prompt improvement, career guidance, learning", "Skills Development", "Advanced", "Coaching sessions per user. Prompt quality improvement over time. User stage progression rate"},
				            // REVENUE ENABLEMENT (sales agents)
				            {"Agent: sales/commercial/customer/crm", "Agent: Sales & Customer", "Sales intelligence, customer insights, deal support, CRM assistance", "Revenue Enablement", "Advanced", "Pipeline velocity, win rate, time-to-quote (CRM). Agent sessions per sales user"},
				            // SERVICE DESK DEFLECTION (IT/support agents)
				            {"Agent: it/service/support/help/remedy/ticket", "Agent: IT & Service Desk", "IT troubleshooting, ticket creation, knowledge base queries", "Service Desk Deflection", "Advanced", "Tickets NOT created (deflection rate). First-contact resolution. Cost per AI resolution vs human"},
				            // COMPLIANCE & TRUST
				            {"Agent: policy/compliance/legal/audit/risk", "Agent: Compliance & Policy", "Policy lookup, compliance checking, risk assessment, audit support", "Compliance & Risk", "Advanced", "DLP incident rate (should decrease). Audit pass rate. Sensitive sessions without flags"},
				            {"SensitivityLabelId present", "Sensitive Content Interaction", "Working with classified or protected content via AI", "Compliance & Risk", "Proficient", "Sensitive AI sessions %. Security flag rate (should be near 0)"},
				            // TECHNICAL CAPABILITY
				            {"Resource=py/js/java/tsx + Active", "Code Writing", "Feature development, scripting, automation", "Coding Capability", "Advanced", "Code files created/modified. Non-tech users writing code (skills expansion)"},
				            {"Resource=py/sql/json/xml + Read", "Code Analysis", "Code review, debugging, understanding codebases", "Coding Capability", "Advanced", "Code reviews via AI. Bug detection rate"},
				            // CONTENT CREATION (visual)
				            {"AppHost=Designer OR png/jpg/svg + Active", "Image Generation", "Marketing visuals, presentations, social content", "Content Output", "Advanced", "Images generated per user. Design tool adoption"},
				            {"Resource=png/jpg/gif + Read", "Image/Media Analysis", "Accessibility descriptions, content cataloguing", "Content Output", "Proficient", "Media files analysed. Accessibility compliance rate"},
				            // PEOPLE & ORG INTELLIGENCE
				            {"Resource=PeopleInferenceAnswer", "People Lookup", "Org navigation, finding experts, team building", "Search Time Saved", "Proficient", "Lookups per user/month. Cross-team collaboration rate (Viva Insights)"},
				            // WORKFLOW AUTOMATION
				            {"Resource=Flow/Connector + Invoke", "Workflow Execution", "Automating approvals, notifications, data flows", "Workflow Triggered", "Advanced", "Flows triggered via AI. Manual steps eliminated per workflow"},
				            // TASK & PROJECT MANAGEMENT
				            {"AppHost=Planner + PlanId/TaskIds", "Task Management", "Sprint planning, task tracking, project coordination", "Task Coordination", "Proficient", "Tasks created/managed via AI. Project delivery velocity"},
				            // COLLABORATION & KNOWLEDGE
				            {"AppHost=Loop/Whiteboard/VivaEngage", "Real-time Collaboration", "Brainstorming, shared editing, team ideation", "Team Collaboration", "Proficient", "Shared sessions per team. Cross-team collaboration (Viva Insights)"},
				            {"AppHost=OneNote", "Note Taking", "Meeting notes, personal knowledge management", "Time Saved (Documents)", "Developing", "Notes created via AI. Meeting follow-up completion rate"},
				            {"AppHost=Forms", "Form/Survey Work", "Feedback collection, quizzes, data gathering", "Team Collaboration", "Developing", "Forms created/analysed. Response rates"},
				            // DOMAIN EXPERTISE (auto-detected agents)
				            {"Agent used >70% by one org group", "Domain-Specific Agent", "Specialist agent serving one function (auto-detected from data)", "Specialist Expertise", "Advanced", "Domain agent sessions per function. Function-specific KPI improvement"},
				            {"Agent used across 5+ org groups", "Cross-Org Agent", "Platform agent serving multiple functions (auto-detected from data)", "Specialist Expertise", "Proficient", "Agent reach across orgs. Cross-org adoption rate"},
				            // RESEARCH & ANALYSIS (agent)
				            {"Agent: research/analyst/insight/intelligence", "Agent: Research & Analysis", "Market research, competitive analysis, data interpretation, trend spotting", "Data-Driven Decisions", "Advanced", "Research sessions per user. Time-to-insight reduction. Analyst productivity (survey)"},
				            // HR & PEOPLE (agent)
				            {"Agent: hr/recruit/talent/onboard/hiring", "Agent: HR & People", "Job descriptions, candidate screening, onboarding guidance, policy Q&A", "HR Process Automation", "Advanced", "HR agent sessions. Time-to-hire reduction. Onboarding completion rate"},
				            // CONTENT GENERATION (agent)
				            {"Agent: summar/draft/translat/content", "Agent: Content Generation", "Drafting communications, summarising documents, translation, content creation", "Content Output", "Advanced", "Content pieces generated per user. Review cycle time reduction"},
				            // DATA & REPORTING (agent)
				            {"Agent: data/report/dashboard/analytics", "Agent: Data & Reporting", "Building reports, querying data, KPI tracking, dashboard creation", "Data-Driven Decisions", "Advanced", "Reports generated per user. Self-service analytics adoption rate"},
				            // KNOWLEDGE BASE (agent)
				            {"Agent: knowledge/faq/wiki/guide/handbook", "Agent: Knowledge Base", "Policy lookup, process guidance, FAQ resolution, documentation search", "Search Time Saved", "Proficient", "KB sessions per user. Support ticket deflection rate. Time-to-answer"},
				            // IDEATION & CREATIVE (agent)
				            {"Agent: ideation/brainstorm/creative/design", "Agent: Ideation & Creative", "Brainstorming, design concepts, creative briefs, innovation workshops", "Content Output", "Advanced", "Creative sessions per user. Ideas generated per session"},
				            // GENERAL PURPOSE (agent - unclassified)
				            {"Agent: no keyword match in name/desc", "Agent: General Purpose", "Unclassified agent interactions - review agent for better categorisation", "General AI Productivity", "Developing", "Should decrease as agent metadata improves. Review agents in this category"},
				            // GENERAL
				            {"AppHost=Office, no resources", "M365 Chat Q&A", "Quick questions in M365 Chat without document grounding", "General AI Productivity", "Beginner", "Sessions per user. Conversion to grounded interactions over time"},
				            {"AppHost=Teams, no resources", "Teams Q&A", "Quick questions in Teams Copilot", "General AI Productivity", "Beginner", "Sessions per user. Conversion to grounded interactions"},
				            {"AppHost=Edge, no resources", "Browser Q&A", "Quick questions in Edge browser", "General AI Productivity", "Beginner", "Sessions per user"},
				            {"No specific signals", "General Q&A", "Catch-all for unclassified interactions", "General AI Productivity", "Beginner", "Should decrease as classification improves"},
				            // GAP FIXES - exact names from M code Behavior_Category output
				            {"Outlook/OutlookSidepane + EmailMessage + Read", "Email Summarising", "Reading and summarising email content via Copilot", "Time Saved (Email)", "Developing", "Survey: mins saved/day on email. Benchmark: 2 min per email summary"},
				            {"No specific resource/plugin signals", "General Chat", "General AI chat without document grounding or specific action", "General AI Productivity", "Beginner", "Sessions per user. Conversion to grounded interactions over time"},
				            {"Resource=png/jpg/gif + Read (spaces)", "Image / Media Analysis", "Accessibility descriptions, content cataloguing, image review", "Content Output", "Proficient", "Media files analysed. Accessibility compliance rate"},
				            // NEW BEHAVIORS FROM FIX 5 (URL routing - unique behavior names for hyperlink classifications)
				            {"resType=http://schema.skype.com/hyperlink + coding URL", "Code Analysis (URL)", "Hyperlink to coding site (GitHub, StackOverflow, npmjs, pypi, docker, kubernetes, etc.)", "Coding Capability", "Advanced", "Coding URL interactions per user. Non-dev users accessing coding resources."},
				            {"resType=http://schema.skype.com/hyperlink + learning URL", "Agent: Coaching (URL)", "Hyperlink to learning platform (Coursera, Udemy, LinkedIn Learning, MS Learn)", "Skills Development", "Developing", "Learning URL interactions. Self-directed learning via Copilot."},
				            // SPREADSHEET (Excel review/assistance — bridge entries for Behavior_Enriched_Full values produced by Audit Logs DAX)
				            {"Resource=xlsx + Read (review)", "Spreadsheet Review", "Reviewing spreadsheets, validating numbers, light analysis", "Spreadsheet Time Saved", "Developing", "Spreadsheets reviewed per user. Time saved on validation"},
				            {"AppHost=Excel + assistance actions", "Excel Assistance", "Excel-native AI help — formulas, formatting, ad-hoc analysis", "Spreadsheet Time Saved", "Proficient", "Excel assistance sessions per user. Self-service analytics adoption"},
				            // FORM / SURVEY WORK (with spaces) — alias of Form/Survey Work emitted by Audit Logs DAX
				            {"AppHost=Forms (spaces variant)", "Form / Survey Work", "Feedback collection, quizzes, data gathering", "Team Collaboration", "Developing", "Forms created/analysed. Response rates"}
				        }
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {
				        {"Signal", type text},
				        {"Behavior", type text},
				        {"Use Case", type text},
				        {"Value Outcome", type text},
				        {"Stage Typical", type text},
				        {"Indicative Org Metric", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

