table 'Chat + Agent Interactions (Audit Logs)'
	lineageTag: be471a18-81ce-45e7-8166-531a052df5d5

	/// Total Copilot prompts submitted
	/// 📈 Volume indicator
	/// 💡 Track growth and trends
	measure PromptsSubmitted = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Message_Id]),'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE")
		formatString: 0
		lineageTag: aa0e8e7e-5e3d-4709-9a73-95cc9be8cd3f

		changedProperty = IsHidden

	/// Users interacting with Copilot agents
	/// 🎯 Target: 20-40% of Chat users
	/// 💡 Higher % = good agent discoverability
	measure UsersInteractingWithAgents =
			-- Counts users of any agent activity: registered agents (have AgentId)
			-- AND autonomous Copilot Studio flows (have Environment="Autonomous Agent"
			-- but blank AgentId). Without the Environment branch, autonomous agents
			-- show zero users and get filtered out of leaderboards.
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			    'Chat + Agent Interactions (Audit Logs)'[Environment] IN {"Agents", "Autonomous Agent"}
			)
		formatString: 0
		lineageTag: 520169a7-8b60-47b3-8c29-548dba3d469d

		changedProperty = IsHidden

	measure 'UsersInteractingWithAgents, Last Month' =
			
			VAR MaxDate = CALCULATE(MAX('Chat + Agent Interactions (Audit Logs)'[CreationDate]), ALL('Chat + Agent Interactions (Audit Logs)'))
			VAR LastMonthStart = EOMONTH(MaxDate, -2) + 1
			VAR Result =
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        'Chat + Agent Interactions (Audit Logs)'[MonthStart] = LastMonthStart,
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			        NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))
			    )
			RETURN Result + 0
		formatString: 0
		lineageTag: 83163a0e-084f-40d7-b612-83a374053e40

		changedProperty = IsHidden

	measure _MaxDate = MAX('Chat + Agent Interactions (Audit Logs)'[CreationDate])
		formatString: General Date
		lineageTag: 8b3aa008-cd02-47e9-88e6-ec53ea7662ea

		changedProperty = IsHidden

	measure _LastMonthStart = EOMONTH([_MaxDate], -2) + 1
		formatString: General Date
		lineageTag: f2974e6e-3a26-4c27-a72c-3a8e6129529f

		changedProperty = IsHidden

	/// Average days agents users are active monthly
	/// ✅ >8 days = strong agent adoption
	/// 💡 Compare to chat-only users
	measure 'Average Agent Active Days Per User' =
			
			AVERAGEX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			        NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))
			    )
			)
		lineageTag: 1ece3323-cea1-459f-9ca4-9d475ed2e359

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average days per week users are active
	/// ✅ >10 days = engaged users
	/// ⚠️ <5 days = low engagement
	/// 💡 Focus on habit formation
	measure 'Average Chat Active Days Per User' =
			
			AVERAGEX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			        ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId])
			    )
			)
		lineageTag: 1871c47e-310d-4eb5-aa25-4b3ef8b060ca

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NoOfActiveChatUsers (Unlicensed)' =
			
			CALCULATE(
			    COUNTROWS(
			        FILTER(
			            VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			            [PromptsSubmitted] > 0
			        )
			    ),
			    'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed"
			)
		formatString: 0
		lineageTag: 385c52b8-89d9-454b-b37e-1a90dd3b5038

		changedProperty = IsHidden

	measure 'NoOfActiveChatUsers (Licensed)' =
			
			CALCULATE(
			    COUNTROWS(
			        FILTER(
			            VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			            [PromptsSubmitted] > 0
			        )
			    ),
			    'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed"
			)
		formatString: 0
		lineageTag: 5ae3fdae-2e6a-432c-830d-841f1fd27c01

	/// Monthly avg actions per user
	/// 📊 Monthly usage intensity
	/// 💡 Benchmark across departments
	measure 'AverageActionsPerUserPerMonth (Licensed Copilot Only)' = ```
			
			
			AVERAGEX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    VAR TotalPrompts =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Message_Id]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),  -- Excludes Agents
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed",
			            ALL('Chat + Agent Interactions (Audit Logs)'[MonthStart])
			        )
			    VAR TotalMonths =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[MonthStart]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed",
			            ALL('Chat + Agent Interactions (Audit Logs)'[MonthStart])
			        )
			    RETURN
			        DIVIDE(TotalPrompts, TotalMonths, 0)
			)
			
			```
		lineageTag: ebdcd3da-36e5-4adc-89ae-cc1f71b07c45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User using most different agents
	/// 🌟 Power user exploring broadly
	/// 💡 Early adopter of new agents
	measure 'Most Versatile Agent' = ```
			
			VAR AgentUserCounts = 
			    ADDCOLUMNS(
			        SUMMARIZE(
			            'Chat + Agent Interactions (Audit Logs)',
			            'Chat + Agent Interactions (Audit Logs)'[AgentName]
			        ),
			        "@UniqueUsers", 
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))
			        )
			    )
			VAR MaxUsers = MAXX(AgentUserCounts, [@UniqueUsers])
			VAR MostVersatile = 
			    FILTER(
			        AgentUserCounts,
			        [@UniqueUsers] = MaxUsers
			    )
			RETURN
			    CONCATENATEX(MostVersatile, 'Chat + Agent Interactions (Audit Logs)'[AgentName], ", ")
			```
		lineageTag: 3673341d-b0ab-42fe-9efa-06440654aa0a

	/// Most used agent by sessions
	/// 🏆 Your champion agent
	/// 💡 Study for success patterns
	measure 'Most Popular Agent' =
			
			-- Lists the agent(s) behind the activity in the current cell.
			-- Identity per row: AgentName when present, else AppHost
			-- (e.g. "Logic App", "Autonomous", "Excel") so Workflow Automation
			-- rows that have no AgentName still surface a meaningful identifier.
			-- Top 3 by row count, comma-joined; suffix " +N more" if there's a tail.
			VAR Tagged =
			    SELECTCOLUMNS(
			        FILTER(
			            'Chat + Agent Interactions (Audit Logs)',
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			            && (
			                ('Chat + Agent Interactions (Audit Logs)'[Environment] IN {"Agents", "Autonomous Agent"})
			                || (
			                    NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName]))
			                        && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> ""
			                )
			            )
			        ),
			        "@Identity",
			            IF(
			                NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName]))
			                    && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> "",
			                'Chat + Agent Interactions (Audit Logs)'[AgentName],
			                COALESCE('Chat + Agent Interactions (Audit Logs)'[AppHost], "Unknown")
			            )
			    )
			VAR IdentityCounts =
			    GROUPBY(
			        Tagged,
			        [@Identity],
			        "@Rows", COUNTX(CURRENTGROUP(), 1)
			    )
			VAR TotalIdentities = COUNTROWS(IdentityCounts)
			VAR Top3 = TOPN(3, IdentityCounts, [@Rows], DESC)
			VAR Names = CONCATENATEX(Top3, [@Identity], ", ", [@Rows], DESC)
			VAR Remainder = TotalIdentities - 3
			RETURN
			    IF(ISBLANK(TotalIdentities) || TotalIdentities = 0,
			        BLANK(),
			        Names & IF(Remainder > 0, " +" & FORMAT(Remainder, "0") & " more", "")
			    )
		lineageTag: 2fcb35a1-90b3-47bf-bc41-4103a2ab5069

	measure 'Average Active Days (Unlicensed)' = ```
			
			
			AVERAGEX(
			    FILTER(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Message_Id]),
			            'Chat + Agent Interactions (Audit Logs)'[Has license] = "FALSE"
			        ) > 0
			    ),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			        'Chat + Agent Interactions (Audit Logs)'[Has license] = "FALSE"
			    )
			)
			
			```
		lineageTag: 8c9066bf-26b1-4451-a735-860c5e86d0a3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Active Days (Unlicensed) - Constant Line' = ```
			
			VAR LastMonthStart = CALCULATE([_LastMonthStart], ALL('Chat + Agent Interactions (Audit Logs)'))
			VAR LastMonthEnd = CALCULATE(EOMONTH([_MaxDate], -1), ALL('Chat + Agent Interactions (Audit Logs)'))
			VAR TotalActiveDays = 
			    CALCULATE(
			        SUMX(
			            VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			            CALCULATE(
			                DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]),
			                'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			            )
			        ),
			        ALL('Chat + Agent Interactions (Audit Logs)'),
			        'Chat + Agent Interactions (Audit Logs)'[Has license] = "FALSE",
			        'Chat + Agent Interactions (Audit Logs)'[InteractionDate] >= LastMonthStart,
			        'Chat + Agent Interactions (Audit Logs)'[InteractionDate] <= LastMonthEnd
			    )
			VAR TotalUsers = 
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        ALL('Chat + Agent Interactions (Audit Logs)'),
			        'Chat + Agent Interactions (Audit Logs)'[Has license] = "FALSE",
			        'Chat + Agent Interactions (Audit Logs)'[InteractionDate] >= LastMonthStart,
			        'Chat + Agent Interactions (Audit Logs)'[InteractionDate] <= LastMonthEnd
			    )
			RETURN
			    DIVIDE(TotalActiveDays, TotalUsers, 0)
			```
		lineageTag: 35e66580-b553-47f3-99a2-a1cbf204077a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Active Days Per User (Chat + Agents)' =
			
			AVERAGEX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			    )
			)
		lineageTag: d80d3423-70f7-4dc3-9dcb-1d3d31e2fc2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// License recommendation score
	/// 🎯 Higher = stronger license candidate
	/// 💡 Based on: usage + engagement + consistency
	measure 'License Priority Score (User)' =
			
			VAR SessionsPW =
			    [Median Chat + Agent Sessions Per User Per Week (Unlicensed)]
			VAR DaysPW =
			    [Median Chat + Agent Active Days Per User Per Week (Unlicensed)]
			VAR Intensity =
			    DIVIDE(SessionsPW, DaysPW, 0)
			RETURN
			IF(
			    SessionsPW <= 0 || DaysPW <= 0,
			    BLANK(),
			    -- Option 1: Simple additive (if you have benchmark values)
			    (0.60 * DIVIDE(SessionsPW, 10, 0)) +     -- normalized to 10 sessions/week
			    (0.30 * DIVIDE(DaysPW, 5, 0)) +          -- normalized to 5 days/week
			    (0.10 * DIVIDE(Intensity, 5, 0))         -- normalized to 5 sessions/day
			)
		lineageTag: ce411199-5b7e-4555-bdaf-dd5d6c00aa3e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// % of licensed Copilot users also using agents
	/// ✅ >30% = excellent
	/// 🟡 15-30% = good
	/// ⚠️ <15% = improve discoverability
	measure '% Copilot Users Using Agents (Licensed)' =
			
			DIVIDE(
			    CALCULATE(
			        [UsersInteractingWithAgents],
			        'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed"
			    ),
			    [NoOfActiveChatUsers (Licensed)],
			    0
			)
		formatString: 0%;-0%;0%
		lineageTag: 27973400-d5dd-44cc-925b-d57a556b8b18

	measure '% Chat Users Using Agents (Unlicensed)' =
			
			DIVIDE(
			    CALCULATE(
			        [UsersInteractingWithAgents],
			        'Chat + Agent Interactions (Audit Logs)'[License Status] <> "M365 Copilot Licensed"
			    ),
			    [NoOfActiveChatUsers (Unlicensed)],
			    0
			)
		formatString: 0%;-0%;0%
		lineageTag: c9d2509a-d2a1-4bfc-8285-b6478a1fad76

	/// All user interaction sessions (chat + agents)
	/// 📈 Track growth trajectory
	/// 💡 Benchmark: 100+ sessions/user/year
	measure 'Total Sessions (All)' =
			
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE")
		formatString: 0
		lineageTag: ff38e089-5b1b-4362-ad9f-c7764496daaa

	/// Total agent interaction sessions
	/// 📈 Track growth over time
	/// 💡 Compare to total chat sessions
	measure 'Total Agent Sessions' = ```
			
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			    NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))
			)
			
			```
		formatString: 0
		lineageTag: 88070138-1838-49f4-bff5-6f328c6e420f

	measure 'Sessions (Licensed Users Only)' =
			
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			    'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed"
			)
		formatString: 0
		lineageTag: 40976c77-12c3-4d9a-aab2-54b7a28c33ad

	measure 'Sessions (Unlicensed Users Only)' =
			
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			    'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed"
			)
		formatString: 0
		lineageTag: c843e9ef-734d-43ff-81ed-8151720b7c0e

	/// Avg sessions for licensed users
	/// 🎯 Target: 25+ sessions/month
	/// 💡 ROI indicator for licenses
	measure 'Average Sessions Per Active User (Licensed)' =
			
			AVERAGEX(
			    FILTER(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed"
			        ) > 0
			    ),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			        'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed"
			    )
			)
		formatString: 0.0
		lineageTag: 3edc553d-f718-46ed-9830-b64b136db58b

	measure 'Average Agent Sessions Per Active Agent User' =
			
			AVERAGEX(
			    FILTER(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))
			        ) > 0
			    ),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			        NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))
			    )
			)
		formatString: 0.0
		lineageTag: 6e9306c6-0ddf-4b97-9729-909c8ad4cdaf

	/// Weekly avg sessions per user
	/// ✅ >5/week = engaged
	/// ⚠️ <2/week = at risk
	/// 💡 Weekly habit indicator
	measure 'Average Chat Sessions Per User Per Week (All Licenses)' = ```
			
			AVERAGEX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    VAR TotalSessions =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            ALL('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    VAR TotalWeeks =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            ALL('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    RETURN
			        DIVIDE(TotalSessions, TotalWeeks, 0)
			)
			
			```
		lineageTag: 7dcf5848-cc04-430b-b0ab-a7fbbe86419e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Sessions Per User Per Week (Licensed)' = ```
			
			AVERAGEX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    VAR TotalSessions =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed",
			            ALL('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    VAR TotalWeeks =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed",
			            ALL('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    RETURN
			        DIVIDE(TotalSessions, TotalWeeks, 0)
			)
			
			
			```
		formatString: 0.0
		lineageTag: 4a78cc26-8103-44a3-9209-1cb880253753

	measure 'Average Chat Sessions Per User Per Week (Unlicensed)' =
			
			AVERAGEX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    VAR TotalSessions =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    VAR TotalWeeks =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    RETURN
			        DIVIDE(TotalSessions, TotalWeeks, 0)
			)
		formatString: 0.0
		lineageTag: f805a594-8185-4853-8e20-d9270fc01069

	/// Median sessions per week (unlicensed)
	/// 📊 Typical user behavior
	/// 💡 Less skewed than average
	measure 'Median Chat + Agent Sessions Per User Per Week (Unlicensed)' =
			
			MEDIANX(
			    FILTER(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed"
			        ) > 0  -- ✓ ADD THIS FILTER
			    ),
			    VAR TotalSessions =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    VAR TotalWeeks =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    RETURN
			        DIVIDE(TotalSessions, TotalWeeks, 0)
			)
		formatString: 0.0
		lineageTag: e36c9b31-f1d3-44d8-bb8d-50ae991bd2ea

	measure 'Average Active Days Per User Per Week (Unlicensed Chat)' =
			
			AVERAGEX(
			    FILTER(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed"
			        ) > 0
			    ),
			    VAR TotalActiveDays =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    VAR TotalWeeks =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    RETURN
			        DIVIDE(TotalActiveDays, TotalWeeks, 0)
			)
		formatString: 0.0
		lineageTag: f88bd7cb-92b2-4d8c-8888-715c1a3705a6

	measure 'Average Active Days Per User Per Week (Licensed Copilot)' =
			
			AVERAGEX(
			    FILTER(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed"
			        ) > 0
			    ),
			    VAR TotalActiveDays =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    VAR TotalWeeks =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    RETURN
			        DIVIDE(TotalActiveDays, TotalWeeks, 0)
			)
		lineageTag: bb05f9d9-66e7-4341-a660-83f651fa1077

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median Chat + Agent Active Days Per User Per Week (Unlicensed)' = ```
			
			MEDIANX(
			    FILTER(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[ThreadId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed"
			        ) > 0
			    ),
			    VAR TotalActiveDays =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    VAR TotalWeeks =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			        )
			    RETURN
			        DIVIDE(TotalActiveDays, TotalWeeks, 0)
			)
			
			```
		formatString: 0.0
		lineageTag: b0ff8ef0-1b72-4efb-8d69-2ccd2b36a8eb

	/// Dynamic ranking with current filters
	/// 📊 Updates with your selections
	/// 💡 Drill to see specific cohorts
	measure 'License Priority Rank (Dynamic)' =
			
			VAR CurrentScore = [License Priority Score (User)]
			VAR IsUserLevel = ISINSCOPE('Chat + Agent Interactions (Audit Logs)'[Audit_UserId])
			
			RETURN
			IF(
			    ISBLANK(CurrentScore),
			    BLANK(),
			    IF(
			        IsUserLevel,
			        // Rank users - ONLY those with unlicensed activity
			        RANKX(
			            FILTER(
			                ALLSELECTED('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			                CALCULATE(
			                    COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			                    'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed"
			                ) > 0
			                && NOT(ISBLANK([License Priority Score (User)]))
			            ),
			            [License Priority Score (User)],
			            ,
			            DESC,
			            DENSE
			        ),
			        // Rank organizations - ONLY those with unlicensed users
			        RANKX(
			            FILTER(
			                ALLSELECTED('Chat + Agent Org Data'[Organization]),
			                CALCULATE(
			                    COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			                    'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed"
			                ) > 0
			                && NOT(ISBLANK([License Priority Score (User)]))
			            ),
			            [License Priority Score (User)],
			            ,
			            DESC,
			            DENSE
			        )
			    )
			)
		formatString: 0
		lineageTag: d45ae6e2-c85c-41ff-99dc-7c4e4065c514

	/// Percentage of all active Copilot users who are also using agents
	/// 🎯 Target: 20-40%
	/// 💡 Higher % = strong agent discoverability and adoption
	measure 'Agent Adoption Rate' = ```
			VAR _AgentUsers = [UsersInteractingWithAgents]
			VAR _AllActiveUsers = 
			    CALCULATE(
			        COUNTROWS(
			            FILTER(
			                VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			                CALCULATE([PromptsSubmitted]) > 0
			            )
			        ),
			        ALL('Chat + Agent Interactions (Audit Logs)'[AgentId]),
			        ALL('Chat + Agent Interactions (Audit Logs)'[AgentName]),
			        ALL('Chat + Agent Interactions (Audit Logs)'[Context_Type]),
			        ALL('Chat + Agent Interactions (Audit Logs)'[Agent_TitleID])
			    )
			RETURN
			    DIVIDE(_AgentUsers, _AllActiveUsers, 0)
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6d870706-d5d2-4a0b-bfc4-ffd858519248

	/// Month-over-month % change in licensed user sessions. Positive = growth, negative = decline.
	measure 'Licensed Sessions MoM %' = ```
			VAR _Current = [Sessions (Licensed Users Only)]
			VAR _Previous = 
			    CALCULATE(
			        [Sessions (Licensed Users Only)],
			        DATEADD(Calendar[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(_Current - _Previous, _Previous, BLANK())
			```
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: 📈 Session Trends
		lineageTag: 52b866ef-cc4d-4c97-b0aa-d984f39a386c

	/// Month-over-month % change in unlicensed user sessions. Positive = growth, negative = decline.
	measure 'Unlicensed Sessions MoM %' = ```
			VAR _Current = [Sessions (Unlicensed Users Only)]
			VAR _Previous = 
			    CALCULATE(
			        [Sessions (Unlicensed Users Only)],
			        DATEADD(Calendar[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(_Current - _Previous, _Previous, BLANK())
			```
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: 📈 Session Trends
		lineageTag: da95b48f-ffc5-4cac-aebd-7eef5c686591

	/// Percentage of interactions involving sensitive data
	measure 'Interactions with Sensitive Data %' =
			VAR SensitiveCount = CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), 'Chat + Agent Interactions (Audit Logs)'[Is_Sensitive] = TRUE)
			VAR TotalCount = COUNTROWS('Chat + Agent Interactions (Audit Logs)')
			RETURN DIVIDE(SensitiveCount, TotalCount, 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: AI Fluency\Behaviors\Modifiers
		lineageTag: ff020001-0001-0001-0001-0000000000c2

	/// User-facing AI task count: prompt rows only (excludes bot replies, traces,
	/// system events). What end-users would call "an AI interaction" — the input
	/// they sent. Used by Executive Headline and the Heatmap Toggle slicer label.
	measure 'AI Tasks' =
			CALCULATE(
			    COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			)
		formatString: #,##0
		displayFolder: AI Fluency\Value Types
		lineageTag: ff030001-0001-0001-0001-000000000047

	/// Agent users
	measure 'Agent Users' = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId])))
		formatString: #,##0
		displayFolder: AI Fluency\Agents - Value
		lineageTag: ff030001-0001-0001-0001-000000000153

	/// All Active Users: Every unique user who has used Copilot or Agents (licensed + unlicensed)
	measure 'All Active Users' = DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId])
		formatString: #,##0
		displayFolder: AI Fluency\Adoption Funnel
		lineageTag: ff020001-0001-0001-0001-000000000204

	/// Beginner Users (this period): <3 behaviors OR <3 active days. Users just getting started.
	measure 'Beginner Users' =
			VAR UserStats =
			ADDCOLUMNS(
			VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			"Behaviors", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Behavior_Category])),
			"HasAgent", CALCULATE(COUNTROWS(FILTER('Chat + Agent Interactions (Audit Logs)', NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName])) && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> ""))) > 0,
			"ActiveDays", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]))
			)
			RETURN COUNTROWS(FILTER(UserStats, NOT([Behaviors] >= 3 && [ActiveDays] >= 3)))
		formatString: #,##0
		displayFolder: AI Fluency\User Stages
		lineageTag: ff020001-0001-0001-0001-000000000301

	/// Developing Users (this period): 3+ behaviors AND 3+ active days (but not Proficient). Consistent multi-workflow use.
	measure 'Developing Users' =
			VAR UserStats =
			ADDCOLUMNS(
			VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			"Behaviors", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Behavior_Category])),
			"HasAgent", CALCULATE(COUNTROWS(FILTER('Chat + Agent Interactions (Audit Logs)', NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName])) && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> ""))) > 0,
			"ActiveDays", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]))
			)
			RETURN COUNTROWS(FILTER(UserStats, [Behaviors] >= 3 && [ActiveDays] >= 3 && NOT([Behaviors] >= 5 && [ActiveDays] >= 8)))
		formatString: #,##0
		displayFolder: AI Fluency\User Stages
		lineageTag: ff020001-0001-0001-0001-000000000302

	/// Proficient Users (this period): 5+ behaviors AND 8+ active days. AI is habitual across many workflows.
	measure 'Proficient Users' =
			VAR UserStats =
			ADDCOLUMNS(
			VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			"Behaviors", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Behavior_Category])),
			"HasAgent", CALCULATE(COUNTROWS(FILTER('Chat + Agent Interactions (Audit Logs)', NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName])) && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> ""))) > 0,
			"ActiveDays", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]))
			)
			RETURN COUNTROWS(FILTER(UserStats, [Behaviors] >= 5 && [ActiveDays] >= 8))
		formatString: #,##0
		displayFolder: AI Fluency\User Stages
		lineageTag: ff020001-0001-0001-0001-000000000303

	/// Proficient Users % (of all active users in this period)
	measure 'Proficient Users %' = DIVIDE([Proficient Users], [All Active Users], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: AI Fluency\User Stages
		lineageTag: ff020001-0001-0001-0001-000000000308

	/// % of active users at Proficient stage — quick maturity indicator for comparing groups
	measure 'Proficient Users % (of Active)' = DIVIDE([Proficient Users], [All Active Users], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: AI Fluency\User Stages
		lineageTag: ff020001-0001-0001-0001-000000000311

	/// Rolling 4-week stage counts — for each week, looks back 4 weeks and assigns stage per user based on that window
	measure '4W Beginner Users' =
			VAR CurrentWeek = MAX('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			VAR WindowStart = CurrentWeek - 21
			VAR UserStats =
			ADDCOLUMNS(
			CALCULATETABLE(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart,
			    'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek,
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			),
			"Behaviors", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Behavior_Category]), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek),
			"HasAgent", CALCULATE(COUNTROWS(FILTER('Chat + Agent Interactions (Audit Logs)', NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName])) && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> "")), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek) > 0,
			"ActiveDays", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek)
			)
			VAR WithStage =
			ADDCOLUMNS(UserStats, "Stage",
			IF([Behaviors] >= 5 && [ActiveDays] >= 8, "Proficient",
			IF([Behaviors] >= 3 && [ActiveDays] >= 3, "Developing",
			"Beginner")))
			RETURN COUNTROWS(FILTER(WithStage, [Stage] = "Beginner"))
		formatString: #,##0
		displayFolder: AI Fluency\User Stages (4-Week Rolling)
		lineageTag: ff020001-0001-0001-0001-000000000501

	measure '4W Developing Users' =
			VAR CurrentWeek = MAX('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			VAR WindowStart = CurrentWeek - 21
			VAR UserStats =
			ADDCOLUMNS(
			CALCULATETABLE(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart,
			    'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek,
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			),
			"Behaviors", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Behavior_Category]), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek),
			"HasAgent", CALCULATE(COUNTROWS(FILTER('Chat + Agent Interactions (Audit Logs)', NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName])) && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> "")), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek) > 0,
			"ActiveDays", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek)
			)
			VAR WithStage =
			ADDCOLUMNS(UserStats, "Stage",
			IF([Behaviors] >= 5 && [ActiveDays] >= 8, "Proficient",
			IF([Behaviors] >= 3 && [ActiveDays] >= 3, "Developing",
			"Beginner")))
			RETURN COUNTROWS(FILTER(WithStage, [Stage] = "Developing"))
		formatString: #,##0
		displayFolder: AI Fluency\User Stages (4-Week Rolling)
		lineageTag: ff020001-0001-0001-0001-000000000502

	measure '4W Proficient Users' =
			VAR CurrentWeek = MAX('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			VAR WindowStart = CurrentWeek - 21
			VAR UserStats =
			ADDCOLUMNS(
			CALCULATETABLE(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart,
			    'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek,
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			),
			"Behaviors", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Behavior_Category]), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek),
			"HasAgent", CALCULATE(COUNTROWS(FILTER('Chat + Agent Interactions (Audit Logs)', NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName])) && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> "")), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek) > 0,
			"ActiveDays", CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[InteractionDate]), 'Chat + Agent Interactions (Audit Logs)'[WeekStart] >= WindowStart, 'Chat + Agent Interactions (Audit Logs)'[WeekStart] <= CurrentWeek)
			)
			VAR WithStage =
			ADDCOLUMNS(UserStats, "Stage",
			IF([Behaviors] >= 5 && [ActiveDays] >= 8, "Proficient",
			IF([Behaviors] >= 3 && [ActiveDays] >= 3, "Developing",
			"Beginner")))
			RETURN COUNTROWS(FILTER(WithStage, [Stage] = "Proficient"))
		formatString: #,##0
		displayFolder: AI Fluency\User Stages (4-Week Rolling)
		lineageTag: ff020001-0001-0001-0001-000000000503

	/// Stage Profile: Top org for current stage context
	measure 'Stage Top Org' =
			VAR OrgTable =
			    ADDCOLUMNS(
			        VALUES('Chat + Agent Org Data'[Organization]),
			        "UserCount",
			        CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]))
			    )
			VAR TopRow = TOPN(1, OrgTable, [UserCount], DESC)
			RETURN MAXX(TopRow, 'Chat + Agent Org Data'[Organization])
		displayFolder: AI Fluency\Stage Profiles
		lineageTag: ff020001-0001-0001-0001-000000000602

	/// Total human-equivalent hours: what AI is handling that humans would otherwise do
	/// Sources: McKinsey 2023, NBER (Brynjolfsson/Noy&Zhang), BCG/Harvard, Forrester TEI 2024
	measure 'Human Equivalent Hours' =
			SUMX(
			    FILTER(
			        'Chat + Agent Interactions (Audit Logs)',
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			    ),
			    DIVIDE(
			        RELATED('Human Time Estimates'[Human Baseline (min)]),
			        60,
			        0
			    )
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\Time Savings
		lineageTag: ff060001-0001-0001-0001-000000000010

	/// Estimated hours saved (30% efficiency gain — Noy & Zhang, Science 2023)
	measure 'Estimated Hours Saved' = [Human Equivalent Hours] * 0.70
		formatString: #,##0.0
		displayFolder: AI Fluency\Time Savings
		lineageTag: ff060001-0001-0001-0001-000000000011

	/// Average augmented skills per user
	measure 'Avg Skills Per User' = ```
			
			    AVERAGEX(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Behavior_Category]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			        )
			    )
			```
		formatString: #,##0.0
		displayFolder: AI Fluency\Augmented Skills
		lineageTag: ff080001-0001-0001-0001-000000000014

	measure 'Hours Saved Per User' = ```
			
			    DIVIDE(
			        [Estimated Hours Saved],
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        0
			    )
			```
		displayFolder: AI Fluency\Time Savings
		lineageTag: f6e1f84b-1a34-4bc7-b296-c5a585fba0ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Productive AI Rate: % of interactions that are Creating + Executing + Orchestrating
	measure 'Productive AI Rate' =
			VAR ProductiveCount =
			    CALCULATE(
			        COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			        'Chat + Agent Interactions (Audit Logs)'[Usage_Mode] IN {"4 - Producing"}
			    )
			VAR TotalCount =
			    CALCULATE(
			        COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			    )
			RETURN DIVIDE(ProductiveCount, TotalCount, 0)
		formatString: 0%;-0%;0%
		displayFolder: AI Fluency\Usage Modes
		lineageTag: ff030001-0001-0001-0001-000000000022

	measure 'Usage Mode Share' = ```
			
			    DIVIDE(
			        CALCULATE(
			            COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			        ),
			        CALCULATE(
			            COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[Usage_Mode])
			        ),
			        0
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: AI Fluency\Usage Modes
		lineageTag: 31b0953a-8e21-43c7-9609-9bd33c63ec8a

	/// % of users in current stage leveraging this Usage Mode, Behavior, or Breakdown (works at all drill levels)
	measure '% of Users in Stage' = ```
			
			    VAR UsersInContext =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			        )
			    VAR TotalUsersInStage =
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[Usage_Mode]),
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[Behavior_Enriched_Full]),
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[Behavior_Category]),
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[Value_Outcome]),
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[Efficiency_Breakdown]),
			            REMOVEFILTERS('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])
			        )
			    RETURN DIVIDE(UsersInContext, TotalUsersInStage, 0)
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: AI Fluency\Usage Modes
		lineageTag: ff030001-0001-0001-0001-000000000029

	/// Specialist jobs performed
	measure 'New Expertise - Jobs' =
			CALCULATE(
			    COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			    NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]))
			)
		formatString: #,##0
		displayFolder: AI Fluency\4 - New Expertise
		lineageTag: ff030001-0001-0001-0001-000000000113

	/// Users accessing specialist capabilities
	measure 'New Expertise - Users' =
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			    NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]))
			)
		formatString: #,##0
		displayFolder: AI Fluency\4 - New Expertise
		lineageTag: ff030001-0001-0001-0001-000000000115

	/// Expert hours delivered per week (org total)
	measure 'New Expertise - Hours Per Week' =
			VAR TotalHrs = CALCULATE([Human Equivalent Hours], NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR Weeks = DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			RETURN DIVIDE(TotalHrs, Weeks, 0)
		formatString: #,##0.0
		displayFolder: AI Fluency\4 - New Expertise
		lineageTag: ff030001-0001-0001-0001-000000000116

	/// ════════════════════════════════════════════
	/// VALUE STORY 1: TIME SAVED (all interactions — everything saves time)
	/// "How much faster are we?" — universal metric across every interaction
	/// ════════════════════════════════════════════
	/// Total hours saved across ALL interactions
	measure 'Efficiency - Hours Saved' = [Human Equivalent Hours]
		formatString: #,##0.0
		displayFolder: AI Fluency\1 - Efficiency
		lineageTag: ff030001-0001-0001-0001-000000000100

	/// Hours saved per active user per active week
	measure 'Efficiency - Hours Per User Per Week' =
			AVERAGEX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			    DIVIDE([Human Equivalent Hours], DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 0)
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\1 - Efficiency
		lineageTag: ff030001-0001-0001-0001-000000000101

	/// Hours saved per week (org total)
	measure 'Efficiency - Hours Per Week' = DIVIDE([Human Equivalent Hours], DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]), 0)
		formatString: 0.00
		displayFolder: AI Fluency\1 - Efficiency
		lineageTag: ff030001-0001-0001-0001-000000000102

	/// Hours saved label "Xh Ym"
	measure 'Efficiency - Label' =
			VAR Hrs = [Efficiency - Hours Per User Per Week]
			VAR WholeHours = INT(Hrs)
			VAR Mins = ROUND((Hrs - WholeHours) * 60, 0)
			RETURN IF(WholeHours > 0, FORMAT(WholeHours, "0") & "h " & FORMAT(Mins, "0") & "m", FORMAT(Mins, "0") & "m")
		displayFolder: AI Fluency\1 - Efficiency
		lineageTag: ff030001-0001-0001-0001-000000000103

	/// Work items created per week (org total)
	measure 'Work Created - Per Week' =
			DIVIDE(
			    CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), 'Chat + Agent Interactions (Audit Logs)'[Usage_Mode] IN {"4 - Producing"}),
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			    0
			)
		formatString: #,##0
		displayFolder: AI Fluency\2 - Work Created
		lineageTag: ff030001-0001-0001-0001-000000000106

	/// Specialist roles active
	measure 'New Expertise - Roles' =
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]),
			    'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			    NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]))
			)
		formatString: #,##0
		displayFolder: AI Fluency\4 - New Expertise
		lineageTag: ff030001-0001-0001-0001-000000000114

	/// Beginner users active this week
	measure 'Beginner Users (Weekly)' =
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "1 - Beginner"
			)
		formatString: #,##0
		displayFolder: AI Fluency\Maturity Score
		lineageTag: ff030001-0001-0001-0001-000000000131

	/// Developing users active this week
	measure 'Developing Users (Weekly)' =
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "2 - Developing"
			)
		formatString: #,##0
		displayFolder: AI Fluency\Maturity Score
		lineageTag: ff030001-0001-0001-0001-000000000132

	/// Proficient users active this week
	measure 'Proficient Users (Weekly)' =
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "3 - Proficient"
			)
		formatString: #,##0
		displayFolder: AI Fluency\Maturity Score
		lineageTag: ff030001-0001-0001-0001-000000000133

	/// Total AI actions performed by agents (Agent Value Tracker — no Environment filter needed)
	measure 'Agent AI Tasks' = CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId])))
		formatString: #,##0
		displayFolder: AI Fluency\Agents - Value
		lineageTag: ff030001-0001-0001-0001-000000000139

	/// Agent AI actions per user per week (both sides filtered to agent rows)
	measure 'Agent AI Tasks Per User Per Week' =
			AVERAGEX(
			    CALCULATETABLE(VALUES('Chat + Agent Interactions (Audit Logs)'[WeekStart]), NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))),
			    DIVIDE(
			        CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))),
			        CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId]))),
			        0
			    )
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\Agents - Value
		lineageTag: ff030001-0001-0001-0001-000000000140

	/// Agent AI actions per week — any activity delivered by any agent
	/// (Studio agents, declarative agents, Logic Apps, autonomous flows).
	/// Counts rows where Environment is "Agents" OR "Autonomous Agent" so
	/// agent-delivered activity that lacks an AgentId GUID still contributes.
	measure 'Agent AI Tasks Per Week' =
			VAR AgentRows = FILTER(
			    'Chat + Agent Interactions (Audit Logs)',
			    'Chat + Agent Interactions (Audit Logs)'[Environment] IN {"Agents", "Autonomous Agent"}
			)
			RETURN
			DIVIDE(
			    COUNTROWS(AgentRows),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			        'Chat + Agent Interactions (Audit Logs)'[Environment] IN {"Agents", "Autonomous Agent"}
			    ),
			    0
			)
		formatString: #,##0
		displayFolder: AI Fluency\Agents - Value
		lineageTag: ff030001-0001-0001-0001-000000000141

	/// Total Copilot AI actions (Copilot Value Tracker — no Environment filter needed)
	measure 'Copilot AI Tasks' = CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Licensed M365 Copilot")
		formatString: #,##0
		displayFolder: AI Fluency\Copilot - Value
		lineageTag: ff030001-0001-0001-0001-000000000154

	/// Copilot AI actions per user per week
	measure 'Copilot AI Tasks Per User Per Week' =
			AVERAGEX(
			    CALCULATETABLE(VALUES('Chat + Agent Interactions (Audit Logs)'[WeekStart]), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Licensed M365 Copilot"),
			    DIVIDE(
			        CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Licensed M365 Copilot"),
			        CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Licensed M365 Copilot"),
			        0
			    )
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\Copilot - Value
		lineageTag: ff030001-0001-0001-0001-000000000155

	/// Copilot AI actions per week
	measure 'Copilot AI Tasks Per Week' =
			DIVIDE(
			    CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Licensed M365 Copilot"),
			    CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Licensed M365 Copilot"),
			    0
			)
		formatString: #,##0
		displayFolder: AI Fluency\Copilot - Value
		lineageTag: ff030001-0001-0001-0001-000000000156

	/// Copilot users (licensed)
	measure 'Copilot Users' = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Licensed M365 Copilot")
		formatString: #,##0
		displayFolder: AI Fluency\Copilot - Value
		lineageTag: ff030001-0001-0001-0001-000000000160

	/// Copilot tasks per active Copilot user (entire period)
	measure 'Copilot AI Tasks Per User' =
			DIVIDE(
			    [Copilot AI Tasks],
			    [Copilot Users],
			    0
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\Copilot - Value
		lineageTag: ff030001-0001-0001-0001-000000000162

	/// Agent tasks per active agent user (entire period)
	measure 'Agent AI Tasks Per User' =
			DIVIDE(
			    [Agent AI Tasks],
			    [Agent Users],
			    0
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\Agents - Value
		lineageTag: ff030001-0001-0001-0001-000000000163

	/// Total AI tasks by unlicensed chat users (Unlicensed Value Tracker — no Environment filter needed)
	measure 'Unlicensed AI Tasks' = CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Unlicensed Chat")
		formatString: #,##0
		displayFolder: AI Fluency\Unlicensed - Value
		lineageTag: ff030001-0001-0001-0001-000000000164

	/// Unlicensed AI tasks per user per week (only active unlicensed users)
	measure 'Unlicensed AI Tasks Per User Per Week' =
			AVERAGEX(
			    CALCULATETABLE(VALUES('Chat + Agent Interactions (Audit Logs)'[WeekStart]), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Unlicensed Chat"),
			    DIVIDE(
			        CALCULATE(COUNTROWS('Chat + Agent Interactions (Audit Logs)'), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Unlicensed Chat"),
			        CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Unlicensed Chat"),
			        0
			    )
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\Unlicensed - Value
		lineageTag: ff030001-0001-0001-0001-000000000165

	/// Unlicensed tasks per active user (entire period)
	measure 'Unlicensed AI Tasks Per User' =
			DIVIDE(
			    [Unlicensed AI Tasks],
			    CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Unlicensed Chat"),
			    0
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\Unlicensed - Value
		lineageTag: ff030001-0001-0001-0001-000000000167

	/// AI Assisted Value: Hours x Hourly Value x Penalty Factor (all adjustable via slicers)
	measure 'AI Assisted Value' = [Human Equivalent Hours] * [Hourly Value Value] * [Penalty Factor Value]
		formatString: $#,##0
		displayFolder: AI Fluency\ROI
		lineageTag: ff0b0001-0001-0001-0001-000000000020

	/// Copilot License Investment: PPUPM x Licensed Users x Months (fixed cost regardless of filter)
	measure 'Copilot License Investment' =
			SUMX(
			    VALUES('Chat + Agent Interactions (Audit Logs)'[MonthStart]),
			    [AI PPUPM Value] *
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        'Chat + Agent Interactions (Audit Logs)'[License Status] = "M365 Copilot Licensed"
			    )
			)
		formatString: $#,##0
		displayFolder: AI Fluency\ROI
		lineageTag: ff0b0001-0001-0001-0001-000000000022

	/// Top Value Outcome by hours saved (dynamic to filters)
	measure 'Top Value Outcome' =
			MAXX(
			    TOPN(1,
			        ADDCOLUMNS(
			            VALUES('Chat + Agent Interactions (Audit Logs)'[Value_Outcome]),
			            "@Hrs", [Human Equivalent Hours]
			        ),
			        [@Hrs], DESC
			    ),
			    'Chat + Agent Interactions (Audit Logs)'[Value_Outcome]
			)
		displayFolder: AI Fluency\1 - Efficiency
		lineageTag: ff030001-0001-0001-0001-000000000175

	measure 'AI Assisted Value Per Week' =
			
			DIVIDE(
			    [AI Assisted Value],
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			    0
			)
		formatString: $#,##0
		displayFolder: AI Fluency\ROI
		lineageTag: 2769b48a-57a1-4acb-8a8b-6e3d70626ad7

		annotation PBI_FormatHint = {"isCustom":true}

	/// Projected annualised value at current adoption (observed value scaled from visible weeks to 52)
	measure 'Projected Annualised Value' =
			VAR WeeksInView = DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart])
			VAR AnnualFactor = DIVIDE(52, MAX(WeeksInView, 1), 0)
			RETURN [AI Assisted Value] * AnnualFactor
		formatString: $#,##0
		displayFolder: AI Fluency\Functional Value
		lineageTag: ff0c0001-0001-0001-0001-000000000044

	/// Autonomy Mix: % of hours saved where humans used Copilot directly (Pattern 1 - Human uses Copilot)
	measure 'Copilot Mix %' =
			DIVIDE(
			    CALCULATE([Human Equivalent Hours], 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Licensed M365 Copilot"),
			    [Human Equivalent Hours],
			    0
			)
		formatString: 0.0%
		displayFolder: AI Fluency\Autonomy Mix
		lineageTag: ff0d0001-0001-0001-0001-000000000001

	/// Autonomy Mix: % of hours saved where humans worked alongside an agent (Pattern 2 - Human uses agent, reviews & approves)
	measure 'Agent-Assisted Mix %' =
			DIVIDE(
			    CALCULATE([Human Equivalent Hours], 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Agents"),
			    [Human Equivalent Hours],
			    0
			)
		formatString: 0.0%
		displayFolder: AI Fluency\Autonomy Mix
		lineageTag: ff0d0001-0001-0001-0001-000000000002

	/// Autonomy Mix: % of hours saved where agents ran workflows autonomously (Pattern 3 - Humans set direction, agents operate)
	measure 'Agent-Autonomous Mix %' =
			DIVIDE(
			    CALCULATE([Human Equivalent Hours], 'Chat + Agent Interactions (Audit Logs)'[Environment] = "Autonomous Agent"),
			    [Human Equivalent Hours],
			    0
			)
		formatString: 0.0%
		displayFolder: AI Fluency\Autonomy Mix
		lineageTag: ff0d0001-0001-0001-0001-000000000003

	measure 'User % (by pattern)' =
			
			DIVIDE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			        ALL('Chat + Agent Interactions (Audit Logs)'[Autonomy_Pattern])
			    ),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: AI Fluency
		lineageTag: a70c9c91-1f55-4d79-abbb-2b32f16485d9

	/// Beginner Users % (of all active users in this period)
	measure 'Beginner Users %' = DIVIDE([Beginner Users], [All Active Users], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: AI Fluency\User Stages
		lineageTag: ff020001-0001-0001-0001-000000000306

	/// Developing Users % (of all active users in this period)
	measure 'Developing Users %' = DIVIDE([Developing Users], [All Active Users], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: AI Fluency\User Stages
		lineageTag: ff020001-0001-0001-0001-000000000307

	/// AI ROI Multiple: AI Assisted Value ÷ Copilot License Investment. Dynamic to all filters.
	measure 'AI ROI' = DIVIDE([AI Assisted Value], [Copilot License Investment], 0)
		formatString: 0.00"x"
		displayFolder: AI Fluency\ROI
		lineageTag: ff0b0001-0001-0001-0001-000000000030

	/// Net ROI ($): AI Assisted Value minus Copilot License Investment (dollar benefit after cost)
	measure 'Net ROI ($)' = [AI Assisted Value] - [Copilot License Investment]
		formatString: $#,##0
		displayFolder: AI Fluency\ROI
		lineageTag: ff0b0001-0001-0001-0001-000000000031

	measure 'Activity Share' = ```
			
			    DIVIDE(
			        CALCULATE(
			            COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			        ),
			        CALCULATE(
			            COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			            'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			            REMOVEFILTERS(
			                'Chat + Agent Interactions (Audit Logs)'[Usage_Mode],
			                'Chat + Agent Interactions (Audit Logs)'[Behavior_Enriched_Full],
			                'Chat + Agent Interactions (Audit Logs)'[Behavior_Category],
			                'Chat + Agent Interactions (Audit Logs)'[Efficiency_Breakdown],
			                'Chat + Agent Interactions (Audit Logs)'[Value_Outcome],
			                'Chat + Agent Interactions (Audit Logs)'[Expertise_Role]
			            )
			        ),
			        0
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: be5a75f5-b45a-4db7-a70f-8f67dd6ba89f

	/// Cowork AI actions (collaborative AI sessions — multi-user real-time)
	measure 'Cowork AI Tasks' =
			CALCULATE(
			    COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			    'Chat + Agent Interactions (Audit Logs)'[Environment] = "Cowork"
			)
		formatString: #,##0
		displayFolder: AI Fluency\Cowork - Value
		lineageTag: ff030001-0001-0001-0001-000000000170

	/// Cowork AI actions per week
	measure 'Cowork AI Tasks Per Week' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			        'Chat + Agent Interactions (Audit Logs)'[Environment] = "Cowork"
			    ),
			    CALCULATE(
			        DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			        'Chat + Agent Interactions (Audit Logs)'[Environment] = "Cowork"
			    ),
			    0
			)
		formatString: #,##0
		displayFolder: AI Fluency\Cowork - Value
		lineageTag: ff030001-0001-0001-0001-000000000171

	/// Cowork users — distinct users with at least one Cowork interaction
	measure 'Cowork Users' =
			CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			    'Chat + Agent Interactions (Audit Logs)'[Environment] = "Cowork"
			)
		formatString: #,##0
		displayFolder: AI Fluency\Cowork - Value
		lineageTag: ff030001-0001-0001-0001-000000000172

	/// Cowork tasks per active Cowork user per active week
	measure 'Cowork AI Tasks Per User Per Week' =
			AVERAGEX(
			    CALCULATETABLE(
			        VALUES('Chat + Agent Interactions (Audit Logs)'[WeekStart]),
			        'Chat + Agent Interactions (Audit Logs)'[Environment] = "Cowork"
			    ),
			    DIVIDE(
			        CALCULATE(
			            COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			            'Chat + Agent Interactions (Audit Logs)'[Environment] = "Cowork"
			        ),
			        CALCULATE(
			            DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),
			            'Chat + Agent Interactions (Audit Logs)'[Environment] = "Cowork"
			        ),
			        0
			    )
			)
		formatString: #,##0.0
		displayFolder: AI Fluency\Cowork - Value
		lineageTag: ff030001-0001-0001-0001-000000000173

	/// Automating AI Rate: % of interactions in Usage_Mode "5 - Automating"
	/// (Workflow Execution, autonomous Copilot Studio agents, Logic Apps, etc.)
	measure 'Automating AI Rate' =
			VAR AutomatingCount =
			    CALCULATE(
			        COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE",
			        'Chat + Agent Interactions (Audit Logs)'[Usage_Mode] IN {"5 - Automating"}
			    )
			VAR TotalCount =
			    CALCULATE(
			        COUNTROWS('Chat + Agent Interactions (Audit Logs)'),
			        'Chat + Agent Interactions (Audit Logs)'[Message_isPrompt] = "TRUE"
			    )
			RETURN DIVIDE(AutomatingCount, TotalCount, 0)
		formatString: 0%;-0%;0%
		displayFolder: AI Fluency\Usage Modes
		lineageTag: ff030001-0001-0001-0001-000000000023

	column CreationDate
		dataType: dateTime
		formatString: General Date
		lineageTag: f8f563c9-ecbc-44b8-b2a0-d0f7c5e1478e
		summarizeBy: none
		sourceColumn: CreationDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Audit_UserId
		dataType: string
		lineageTag: db4eb025-51a3-4bb9-8da1-c029d8f5737d
		summarizeBy: none
		sourceColumn: Audit_UserId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AppHost
		dataType: string
		lineageTag: 8a5b8c19-423f-4b0a-bc26-6460dc150cf4
		summarizeBy: none
		sourceColumn: AppHost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Context_Type
		dataType: string
		lineageTag: 56cf4a16-b261-4959-87bf-b36a731234c2
		summarizeBy: none
		sourceColumn: Context_Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Message_Id
		dataType: string
		lineageTag: b353fc05-4be9-463b-a101-98d251ff770a
		summarizeBy: none
		sourceColumn: Message_Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Message_isPrompt
		dataType: string
		lineageTag: 1ab885ff-bf49-4a6a-882a-3e24ea057f82
		summarizeBy: none
		sourceColumn: Message_isPrompt

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ModelTransparencyDetails_ModelName
		dataType: string
		lineageTag: cdef958f-8f12-4880-98bc-32853175308c
		summarizeBy: none
		sourceColumn: ModelTransparencyDetails_ModelName

		annotation SummarizationSetBy = Automatic

	column AgentId
		dataType: string
		lineageTag: 0e1ee794-900e-42a3-a011-4559a18d18bb
		summarizeBy: none
		sourceColumn: AgentId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AgentName
		dataType: string
		lineageTag: f84e3a41-98c1-4efe-a231-a4571f1e24b6
		summarizeBy: none
		sourceColumn: AgentName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Has license'
		dataType: string
		lineageTag: 9f8f87a7-b587-498d-94a1-1f8087aedde7
		summarizeBy: none
		sourceColumn: Has license

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AISystemPlugin_Id
		dataType: string
		lineageTag: fea0ad97-dfa5-4153-b300-a1c4519ae1d3
		summarizeBy: none
		sourceColumn: AISystemPlugin_Id

		annotation SummarizationSetBy = Automatic

	column AISystemPlugin_Name
		dataType: string
		lineageTag: ed50fb74-23fe-4f39-9c72-82447b1a868a
		summarizeBy: none
		sourceColumn: AISystemPlugin_Name

		annotation SummarizationSetBy = Automatic

	column 'Agent Last Used Date' =
			LOOKUPVALUE(
			    AgentMetrics[AgentLastUsedDate],
			    AgentMetrics[AgentName],
			    'Chat + Agent Interactions (Audit Logs)'[AgentName]
			)
		formatString: General Date
		lineageTag: 8704c57b-fb9f-453b-b02d-cd18226f282b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Agent_TitleID
		dataType: string
		lineageTag: dfec8665-8f8a-4e31-bbf0-e573a2f92b5e
		summarizeBy: none
		sourceColumn: Agent_TitleID

		annotation SummarizationSetBy = Automatic

	column ThreadId
		dataType: string
		lineageTag: 469cb1bc-2c4f-4875-97f7-4a154ab181aa
		summarizeBy: none
		sourceColumn: ThreadId

		annotation SummarizationSetBy = Automatic

	column AccessedResource_Type
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000001
		summarizeBy: none
		sourceColumn: AccessedResource_Type

		annotation SummarizationSetBy = Automatic

	column AccessedResource_Action
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: AccessedResource_Action

		annotation SummarizationSetBy = Automatic

	column SensitivityLabelId
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000007
		summarizeBy: none
		sourceColumn: SensitivityLabelId

		annotation SummarizationSetBy = Automatic

	/// User maturity stage — now a single RELATED lookup against UserMonthMetrics[UserStage]
	/// (pre-computed once per user-month instead of per-row CALCULATETABLE).
	column User_Stage_Maturity = RELATED('UserMonthMetrics'[UserStage])
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000015
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Actionable source label: Behavior + where it happened (app/agent/plugin)
	column Behavior_Source =
			VAR Behavior = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Category]
			VAR Env = 'Chat + Agent Interactions (Audit Logs)'[Environment]
			VAR Agent = 'Chat + Agent Interactions (Audit Logs)'[AgentName]
			VAR Plugin = 'Chat + Agent Interactions (Audit Logs)'[AISystemPlugin_Name]
			VAR App = 'Chat + Agent Interactions (Audit Logs)'[AppHost]
			VAR Enriched = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Enriched]
			VAR Source =
			    IF(Env = "Autonomous Agent", "Autonomous Agent" & IF(NOT(ISBLANK(Agent)) && Agent <> "", ": " & Agent, ""),
			    IF(Env = "Agents" && NOT(ISBLANK(Agent)) && Agent <> "", "Agent: " & Agent,
			    IF(NOT(ISBLANK(Plugin)) && Plugin <> "", App & " (" & Plugin & ")",
			    IF(NOT(ISBLANK(App)) && App <> "", App,
			    "Copilot Chat"))))
			RETURN
			    Behavior & " → " & Source
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000016
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Enhanced enrichment using Agent Description + Capabilities from Agents 365 (via RELATED)
	column Behavior_Enriched_Full =
			VAR BaseEnriched = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Enriched]
			VAR Env = 'Chat + Agent Interactions (Audit Logs)'[Environment]
			VAR NeedsEnhancement = Env = "Agents" && BaseEnriched = "Agent: General Purpose"
			VAR AgentDesc = IF(NeedsEnhancement, LOWER(RELATED('Agents 365'[Agent description])), "")
			VAR AgentActions = IF(NeedsEnhancement, LOWER(RELATED('Agents 365'[Custom actions])), "")
			VAR HasCode = IF(NeedsEnhancement, RELATED('Agents 365'[Can use code interpreter]) = "Yes", FALSE())
			VAR HasImages = IF(NeedsEnhancement, RELATED('Agents 365'[Can generate images using user prompt]) = "Yes", FALSE())
			VAR HasSP = IF(NeedsEnhancement, RELATED('Agents 365'[Can read Sharepoint sites and files]) = "Yes", FALSE())
			VAR SearchText = AgentDesc & " " & AgentActions
			VAR IsCoaching = CONTAINSSTRING(SearchText, "coach") || CONTAINSSTRING(SearchText, "mentor") || CONTAINSSTRING(SearchText, "learning") || CONTAINSSTRING(SearchText, "training") || CONTAINSSTRING(SearchText, "skill")
			VAR IsResearch = CONTAINSSTRING(SearchText, "research") || CONTAINSSTRING(SearchText, "analyst") || CONTAINSSTRING(SearchText, "analy") || CONTAINSSTRING(SearchText, "insight") || CONTAINSSTRING(SearchText, "intelligence")
			VAR IsSales = CONTAINSSTRING(SearchText, "sales") || CONTAINSSTRING(SearchText, "commercial") || CONTAINSSTRING(SearchText, "customer") || CONTAINSSTRING(SearchText, "crm") || CONTAINSSTRING(SearchText, "pipeline") || CONTAINSSTRING(SearchText, "prospect") || CONTAINSSTRING(SearchText, "deal")
			VAR IsHR = CONTAINSSTRING(SearchText, "recruit") || CONTAINSSTRING(SearchText, "talent") || CONTAINSSTRING(SearchText, "onboard") || CONTAINSSTRING(SearchText, "hiring") || CONTAINSSTRING(SearchText, "employee") || CONTAINSSTRING(SearchText, "human resource") || CONTAINSSTRING(SearchText, "job description")
			VAR IsCompliance = CONTAINSSTRING(SearchText, "policy") || CONTAINSSTRING(SearchText, "compliance") || CONTAINSSTRING(SearchText, "legal") || CONTAINSSTRING(SearchText, "audit") || CONTAINSSTRING(SearchText, "risk") || CONTAINSSTRING(SearchText, "governance")
			VAR IsIT = CONTAINSSTRING(SearchText, "support") || CONTAINSSTRING(SearchText, "helpdesk") || CONTAINSSTRING(SearchText, "troubleshoot") || CONTAINSSTRING(SearchText, "ticket") || CONTAINSSTRING(SearchText, "incident") || CONTAINSSTRING(SearchText, "service desk")
			VAR IsContent = CONTAINSSTRING(SearchText, "summar") || CONTAINSSTRING(SearchText, "draft") || CONTAINSSTRING(SearchText, "translat") || CONTAINSSTRING(SearchText, "content") || CONTAINSSTRING(SearchText, "communications")
			VAR IsData = CONTAINSSTRING(SearchText, "data") || CONTAINSSTRING(SearchText, "report") || CONTAINSSTRING(SearchText, "dashboard") || CONTAINSSTRING(SearchText, "analytics") || CONTAINSSTRING(SearchText, "metric")
			VAR IsKnowledge = CONTAINSSTRING(SearchText, "knowledge") || CONTAINSSTRING(SearchText, "faq") || CONTAINSSTRING(SearchText, "wiki") || CONTAINSSTRING(SearchText, "guide") || CONTAINSSTRING(SearchText, "handbook") || CONTAINSSTRING(SearchText, "documentation")
			VAR IsCreative = CONTAINSSTRING(SearchText, "brainstorm") || CONTAINSSTRING(SearchText, "creative") || CONTAINSSTRING(SearchText, "design") || CONTAINSSTRING(SearchText, "innovat")
			RETURN
			    IF(NOT(NeedsEnhancement), BaseEnriched,
			    IF(IsCoaching, "Agent: Coaching",
			    IF(IsResearch, "Agent: Research & Analysis",
			    IF(IsSales, "Agent: Sales & Customer",
			    IF(IsHR, "Agent: HR & People",
			    IF(IsCompliance, "Agent: Compliance & Policy",
			    IF(IsIT, "Agent: IT & Service Desk",
			    IF(IsContent, "Agent: Content Generation",
			    IF(IsData, "Agent: Data & Reporting",
			    IF(IsKnowledge, "Agent: Knowledge Base",
			    IF(IsCreative, "Agent: Ideation & Creative",
			    IF(HasCode, "Agent: Data & Reporting",
			    IF(HasImages, "Agent: Ideation & Creative",
			    IF(HasSP, "Agent: Knowledge Base",
			    "Agent: General Purpose"))))))))))))))
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000018
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AccessedResource_SiteUrl
		dataType: string
		lineageTag: b67ef0d0-01d8-4bc2-a2ef-0ea215119fd5
		summarizeBy: none
		sourceColumn: AccessedResource_SiteUrl

		annotation SummarizationSetBy = Automatic

	/// Behavior classification: resource-level signals first (accurate per expanded row),
	/// then context/appHost fallback (shared across event — only for rows with no resource info)
	column Behavior_Category =
			VAR appHost = LOWER('Chat + Agent Interactions (Audit Logs)'[AppHost])
			VAR ctxType = LOWER('Chat + Agent Interactions (Audit Logs)'[Context_Type])
			VAR resType = LOWER('Chat + Agent Interactions (Audit Logs)'[AccessedResource_Type])
			VAR resAction = LOWER('Chat + Agent Interactions (Audit Logs)'[AccessedResource_Action])
			VAR siteUrl = LOWER('Chat + Agent Interactions (Audit Logs)'[AccessedResource_SiteUrl])
			VAR pluginId = LOWER('Chat + Agent Interactions (Audit Logs)'[AISystemPlugin_Id])
			VAR isActive = CONTAINSSTRING(resAction, "send") || CONTAINSSTRING(resAction, "draft") || CONTAINSSTRING(resAction, "create") || CONTAINSSTRING(resAction, "post") || CONTAINSSTRING(resAction, "invoke") || CONTAINSSTRING(resAction, "write") || CONTAINSSTRING(resAction, "patch") || CONTAINSSTRING(resAction, "execute")
			VAR FromResource =
			    IF(resAction IN {"sendemailv2","draftemail","senddraftemail","updatedraftemail"}, "Email Drafting",
			    IF(resType = "emailmessage" && isActive, "Email Drafting",
			    IF(resType = "emailmessage", "Email Summarising",
			    IF(resAction = "mcp_meetingmanagement", "Meeting Scheduling",
			    IF(resType IN {"event","teamsmeeting"}, "Meeting Prep",
			    IF(resAction IN {"postmessagetoconversation","createchat"}, "Teams Messaging",
			    IF(resType IN {"teamsmessage","teamschat","teamschannel"}, "Teams Messaging",
			    IF(resType IN {"flow","connector","http"}, "Workflow Execution",
			    IF(resAction IN {"executedatasetquery","getitems","getalltables","gettableviews"}, "Data Querying",
			    IF(resType IN {"xlsx","csv","xlsm","xlsb","xls"}, IF(isActive, "Excel Assistance", "Spreadsheet Review"),
			    IF(resType = "peopleinferenceanswer", "People Lookup",
			    IF(resType = "listitem" || resType = "aspx", "Enterprise Searching",
			    IF(resType = "websearchquery", "Web Searching",
			    IF(resType = "pdf", "PDF Analysis",
			    IF(resType IN {"py","js","java","tsx","jsx","css","php","sh"} && isActive, "Code Writing",
			    IF(resType IN {"py","sql","js","java","json","xml","html","yaml","yml","txt"}, "Code Analysis",
			    IF(resType IN {"png","jpg","jpeg","svg","gif"} && isActive, "Image Generation",
			    IF(resType IN {"png","jpg","jpeg","gif"}, "Image / Media Analysis",
			    IF(resType IN {"streamvideo","mp4","mov","webm","mkv"}, "Video Summarising",
			    IF(resType IN {"planid","taskids"}, "Task Management",
			    IF(resType = "looppage", "Real-time Collaboration",
			    IF(resType = "http://schema.skype.com/hyperlink" && (CONTAINSSTRING(siteUrl, "github.com") || CONTAINSSTRING(siteUrl, "stackoverflow.com") || CONTAINSSTRING(siteUrl, "npmjs.com") || CONTAINSSTRING(siteUrl, "pypi.org") || CONTAINSSTRING(siteUrl, "docker.com") || CONTAINSSTRING(siteUrl, "kubernetes.io") || CONTAINSSTRING(siteUrl, "leetcode.com")), "Code Analysis",
			    IF(resType = "http://schema.skype.com/hyperlink" && (CONTAINSSTRING(siteUrl, "learning.cloud.microsoft") || CONTAINSSTRING(siteUrl, "coursera.org") || CONTAINSSTRING(siteUrl, "udemy.com")), "Agent: Coaching",
			    IF(resType = "http://schema.skype.com/hyperlink" && CONTAINSSTRING(siteUrl, "sharepoint.com"), "Enterprise Searching",
			    IF(resType IN {"external","http"} || resType = "http://schema.skype.com/hyperlink", "Web Searching",
			    IF(resType IN {"docx","doc","rtf"} && isActive, "Document Drafting",
			    IF(resType IN {"docx","doc","rtf"} && resAction = "read", "File Retrieval",
			    IF(resType IN {"docx","doc","rtf"}, "Document Summarising",
			    IF(resType IN {"pptx","ppt","potx"} && isActive, "Presentation Creation",
			    IF(resType IN {"pptx","ppt","potx"} && resAction = "read", "File Retrieval",
			    IF(resType IN {"pptx","ppt","potx"}, "Presentation Summarising",
			    IF(CONTAINSSTRING(siteUrl, "service-now.com") || CONTAINSSTRING(siteUrl, "servicenow.com"), "Agent: IT & Service Desk",
			    IF(CONTAINSSTRING(siteUrl, "dynamics.com"), "Agent: Sales & Customer",
			    BLANK())))))))))))))))))))))))))))))))))
			VAR FromPlugin =
			    IF(pluginId = "enterprisesearch", "Enterprise Searching", BLANK())
			VAR FromContext =
			    IF(ctxType = "teamsmeeting", "Meeting Prep",
			    IF(ctxType = "streamvideo", "Video Summarising",
			    IF(ctxType = "docx", IF(appHost = "word" && isActive, "Document Drafting", "Document Summarising"),
			    IF(ctxType IN {"xlsx","xlsm","xlsb","xls","csv"}, "Spreadsheet Review",
			    IF(ctxType IN {"pptx","pptm"}, IF(appHost = "powerpoint" && isActive, "Presentation Creation", "Presentation Summarising"),
			    IF(ctxType IN {"teamschat","teamschannel"}, "Teams Messaging",
			    IF(ctxType = "aspx", "Enterprise Searching",
			    IF((appHost = "outlook" || appHost = "outlooksidepane") && isActive, "Email Drafting",
			    IF(appHost = "outlook" || appHost = "outlooksidepane", "Email Summarising",
			    IF(appHost = "excel", "Excel Assistance",
			    IF(appHost = "word" && isActive, "Document Drafting",
			    IF(appHost = "word", "Document Summarising",
			    IF(appHost = "powerpoint" && isActive, "Presentation Creation",
			    IF(appHost = "powerpoint", "Presentation Summarising",
			    IF(appHost = "stream", "Video Summarising",
			    IF(appHost = "sharepoint", "SharePoint Access",
			    IF(appHost = "designer", "Image Generation",
			    IF(appHost = "onenote", "Note Taking",
			    IF(appHost = "forms", "Form / Survey Work",
			    IF(appHost = "planner", "Task Management",
			    IF(appHost IN {"loop","whiteboard","vivaengage"}, "Real-time Collaboration",
			    IF(appHost = "copilot studio", "Domain-Specific Agent",
			    IF(appHost IN {"autonomous","logic app"}, "Workflow Execution",
			    IF(appHost IN {"datawarehousing core","power bi"}, "Data Querying",
			    "General Chat"))))))))))))))))))))))))
			RETURN
			    IF(NOT(ISBLANK(FromResource)), FromResource,
			    IF(NOT(ISBLANK(FromPlugin)), FromPlugin,
			    FromContext))
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000003
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Value_Outcome =
			VAR behavior = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Enriched]
			VAR env = 'Chat + Agent Interactions (Audit Logs)'[Environment]
			VAR isSensitive = 'Chat + Agent Interactions (Audit Logs)'[Is_Sensitive]
			RETURN
			    IF(behavior IN {"Email Summarising","Email Triage","Email Thread Summary"}, "Time Saved (Email)",
			    IF(behavior IN {"Meeting Prep","Video Summarising"}, "Time Saved (Meetings)",
			    IF(behavior IN {"Document Summarising","Presentation Summarising","Note Taking"}, "Time Saved (Documents)",
			    IF(behavior IN {"Web Searching","Enterprise Searching","File Retrieval","PDF Analysis","SharePoint Access","People Lookup","Agent: Knowledge Base"}, "Search Time Saved",
			    IF(behavior IN {"Teams Messaging","Meeting Scheduling"}, "Communication Time Saved",
			    IF(behavior IN {"Spreadsheet Review","Spreadsheet Analysis","Excel Assistance"}, "Spreadsheet Time Saved",
			    IF(behavior IN {"Email Drafting","Document Drafting","Presentation Creation","Image Generation","Image / Media Analysis","Image/Media Analysis","Agent: Content Generation","Agent: Ideation & Creative"}, "Content Output",
			    IF(behavior IN {"Real-time Collaboration","Form / Survey Work"}, "Team Collaboration",
			    IF(behavior = "Workflow Execution" || env = "Autonomous Agent", "Workflow Automation",
			    IF(behavior = "Task Management", "Task Coordination",
			    IF(isSensitive && env <> "Agents" && env <> "Autonomous Agent", "Compliance & Risk",
			    IF(behavior IN {"Data Querying","Agent: Data & Reporting","Agent: Research & Analysis"}, "Data-Driven Decisions",
			    IF(behavior IN {"Code Writing","Code Analysis","Code Analysis (URL)"}, "Coding Capability",
			    IF(behavior IN {"Agent: Coaching","Agent: Coaching (URL)"}, "Skills Development",
			    IF(behavior = "Agent: Sales & Customer", "Revenue Enablement",
			    IF(behavior = "Agent: IT & Service Desk", "Service Desk Deflection",
			    IF(behavior = "Agent: Compliance & Policy", "Compliance & Risk",
			    IF(behavior = "Agent: HR & People", "HR Expertise",
			    IF(behavior IN {"Domain-Specific Agent","Cross-Org Agent"}, "Specialist Expertise",
			    "General AI Productivity")))))))))))))))))))
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000008
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Agent-name-based reclassification of generic Q&A into a specific agent category (needed for downstream logic)
	column Behavior_Enriched =
			VAR behavior = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Category]
			VAR agentName = LOWER('Chat + Agent Interactions (Audit Logs)'[AgentName])
			VAR env = 'Chat + Agent Interactions (Audit Logs)'[Environment]
			RETURN
			    IF(env <> "Agents" && env <> "Autonomous Agent", behavior,
			    IF(NOT(behavior IN {"General Q&A","M365 Chat Q&A","Teams Q&A","Browser Q&A","General Chat"}), behavior,
			    IF(CONTAINSSTRING(agentName, "coach") || CONTAINSSTRING(agentName, "mentor") || CONTAINSSTRING(agentName, "learning") || CONTAINSSTRING(agentName, "career"), "Agent: Coaching",
			    IF(CONTAINSSTRING(agentName, "research") || CONTAINSSTRING(agentName, "analyst") || CONTAINSSTRING(agentName, "analy"), "Agent: Research & Analysis",
			    IF(CONTAINSSTRING(agentName, "sales") || CONTAINSSTRING(agentName, "commercial") || CONTAINSSTRING(agentName, "customer") || CONTAINSSTRING(agentName, "crm") || CONTAINSSTRING(agentName, "revenue"), "Agent: Sales & Customer",
			    IF(CONTAINSSTRING(agentName, "hr") || CONTAINSSTRING(agentName, "recruit") || CONTAINSSTRING(agentName, "talent") || CONTAINSSTRING(agentName, "onboard") || CONTAINSSTRING(agentName, "people"), "Agent: HR & People",
			    IF(CONTAINSSTRING(agentName, "policy") || CONTAINSSTRING(agentName, "compliance") || CONTAINSSTRING(agentName, "legal") || CONTAINSSTRING(agentName, "audit") || CONTAINSSTRING(agentName, "risk"), "Agent: Compliance & Policy",
			    IF(CONTAINSSTRING(agentName, "service") || CONTAINSSTRING(agentName, "support") || CONTAINSSTRING(agentName, "help") || CONTAINSSTRING(agentName, "ticket") || CONTAINSSTRING(agentName, "incident"), "Agent: IT & Service Desk",
			    IF(CONTAINSSTRING(agentName, "summar") || CONTAINSSTRING(agentName, "draft") || CONTAINSSTRING(agentName, "translat") || CONTAINSSTRING(agentName, "editor"), "Agent: Content Generation",
			    IF(CONTAINSSTRING(agentName, "data") || CONTAINSSTRING(agentName, "report") || CONTAINSSTRING(agentName, "dashboard") || CONTAINSSTRING(agentName, "metric"), "Agent: Data & Reporting",
			    IF(CONTAINSSTRING(agentName, "knowledge") || CONTAINSSTRING(agentName, "faq") || CONTAINSSTRING(agentName, "wiki") || CONTAINSSTRING(agentName, "buddy") || CONTAINSSTRING(agentName, "guide"), "Agent: Knowledge Base",
			    IF(CONTAINSSTRING(agentName, "idea") || CONTAINSSTRING(agentName, "brainstorm") || CONTAINSSTRING(agentName, "creative") || CONTAINSSTRING(agentName, "design"), "Agent: Ideation & Creative",
			    "Agent: General Purpose"))))))))))))
		dataType: string
		isHidden
		lineageTag: ff030001-0001-0001-0001-000000000012
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Alias of User_Stage_Maturity. Points to the other column to avoid duplicate computation.
	column User_Stage = 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity]
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000013
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AccessedResource_SensitivityLabelId
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000019
		summarizeBy: none
		sourceColumn: AccessedResource_SensitivityLabelId

		annotation SummarizationSetBy = Automatic

	column WeekStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 120a5150-5b30-4d85-892c-8b604f4fa54e
		summarizeBy: none
		sourceColumn: WeekStart

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column InteractionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35fa7604-15bb-4d35-9c30-ed15e09a220b
		summarizeBy: none
		sourceColumn: InteractionDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 259ab0b4-609f-45d7-986a-919bc3627b3c
		summarizeBy: none
		sourceColumn: MonthStart

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// AI Usage Mode (4-stage Bloom's-aligned maturity model)
	/// 1-Asking (Remember) → 2-Consuming (Understand) → 3-Finding (Apply) → 4-Producing (Create + Expert)
	column Usage_Mode =
			VAR behavior = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Enriched_Full]
			VAR env = 'Chat + Agent Interactions (Audit Logs)'[Environment]
			VAR appHost = LOWER('Chat + Agent Interactions (Audit Logs)'[AppHost])
			VAR appIdentity = LOWER(COALESCE('Chat + Agent Interactions (Audit Logs)'[AppIdentity_AppId], ""))
			VAR isAutomating =
			    env = "Autonomous Agent"
			    || appHost = "copilot studio"
			    || CONTAINSSTRING(appIdentity, "copilot.studio")
			    || behavior IN {"Workflow Execution","Task Management","Meeting Scheduling"}
			RETURN
			    IF(isAutomating, "5 - Automating",
			    IF(behavior IN {"Email Drafting","Document Drafting","Presentation Creation","Image Generation","Code Writing","Code Analysis","Code Analysis (URL)","Data Querying","Spreadsheet Analysis","Excel Assistance","Agent: Content Generation","Agent: Ideation & Creative","Agent: Research & Analysis","Agent: Data & Reporting","Agent: Sales & Customer","Agent: HR & People","Agent: IT & Service Desk","Agent: Compliance & Policy","Agent: Coaching","Agent: Coaching (URL)","Domain-Specific Agent","Cross-Org Agent","Form / Survey Work","Real-time Collaboration"}, "4 - Producing",
			    IF(behavior IN {"Document Summarising","Email Summarising","Email Thread Summary","Email Triage","Presentation Summarising","Video Summarising","Meeting Prep","Note Taking","Teams Messaging","Image / Media Analysis","Image/Media Analysis"}, "3 - Consuming",
			    IF(behavior IN {"Web Searching","Enterprise Searching","PDF Analysis","SharePoint Access","File Retrieval","People Lookup","Agent: Knowledge Base","Spreadsheet Review"}, "2 - Finding",
			    "1 - Asking"))))
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000020
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Skill role AI is augmenting — broader than the original specialist-only definition.
	/// Covers comms, content, presentations, design, meetings, research, data, collaboration
	/// in addition to the strict specialist roles. 18 distinct roles total.
	/// Generic Q&A / chat catch-alls remain BLANK by design (no clear skill being augmented).
	column Expertise_Role =
			VAR behavior = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Enriched_Full]
			RETURN
			    -- Specialist roles (strict — kept from original definition)
			    IF(behavior IN {"Data Querying","Agent: Data & Reporting","Spreadsheet Analysis"}, "Data Analyst",
			    IF(behavior IN {"Code Writing","Code Analysis","Code Analysis (URL)"}, "Software Engineer",
			    IF(behavior IN {"Agent: Research & Analysis"}, "Business Analyst",
			    IF(behavior IN {"Agent: Compliance & Policy","Sensitive Content Interaction"}, "Compliance Specialist",
			    IF(behavior IN {"Agent: Sales & Customer"}, "Sales Consultant",
			    IF(behavior IN {"Agent: IT & Service Desk"}, "IT Specialist",
			    IF(behavior IN {"Agent: HR & People"}, "HR Specialist",
			    IF(behavior IN {"Agent: Coaching","Agent: Coaching (URL)"}, "Coach",
			    IF(behavior IN {"Workflow Execution","Task Management"}, "Automation Engineer",
			    IF(behavior IN {"Domain-Specific Agent","Cross-Org Agent"}, "Domain Expert",
			    -- Broader skill roles (NEW — knowledge-worker fundamentals AI is augmenting)
			    IF(behavior IN {"Email Drafting","Email Triage","Email Summarising","Email Thread Summary","Teams Messaging"}, "Communications Specialist",
			    IF(behavior IN {"Document Drafting","Agent: Content Generation","Note Taking","Document Summarising"}, "Content Writer",
			    IF(behavior IN {"Presentation Creation","Presentation Summarising"}, "Presentation Designer",
			    IF(behavior IN {"Image Generation","Image/Media Analysis","Image / Media Analysis","Agent: Ideation & Creative"}, "Visual Designer",
			    IF(behavior IN {"Meeting Prep","Meeting Scheduling","Video Summarising"}, "Meeting Coordinator",
			    IF(behavior IN {"Web Searching","Enterprise Searching","PDF Analysis","SharePoint Access","File Retrieval","People Lookup","Agent: Knowledge Base"}, "Researcher",
			    IF(behavior IN {"Spreadsheet Review","Excel Assistance"}, "Spreadsheet Specialist",
			    IF(behavior IN {"Real-time Collaboration","Form / Survey Work","Form/Survey Work"}, "Collaboration Lead",
			    BLANK()))))))))))))))))))
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000095
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Efficiency breakdown: where is time being saved?
	/// Revised Efficiency Breakdown: 12 categories validated across 4 datasets
	column Efficiency_Breakdown =
			VAR behavior = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Enriched_Full]
			VAR cat = 'Chat + Agent Interactions (Audit Logs)'[Behavior_Category]
			RETURN
			    IF(behavior IN {"Email Summarising","Email Triage","Email Thread Summary","Email Drafting"}, "Email",
			    IF(behavior IN {"Document Summarising","Note Taking","Document Drafting","Agent: Content Generation"}, "Document Assistance",
			    IF(behavior IN {"Presentation Summarising","Presentation Creation"}, "Presentations",
			    IF(behavior IN {"Meeting Prep","Video Summarising","Meeting Scheduling"}, "Meetings",
			    IF(behavior IN {"Web Searching","Enterprise Searching","PDF Analysis","SharePoint Access","File Retrieval","People Lookup","Agent: Knowledge Base","Agent: Research & Analysis"}, "Search & Research",
			    IF(behavior IN {"Spreadsheet Review","Excel Assistance","Spreadsheet Analysis","Data Querying","Agent: Data & Reporting"}, "Data & Spreadsheets",
			    IF(behavior IN {"Image Generation","Image / Media Analysis","Image/Media Analysis","Agent: Ideation & Creative","Code Writing","Code Analysis","Code Analysis (URL)"}, "Creative & Technical",
			    IF(behavior IN {"Teams Messaging","Real-time Collaboration","Form / Survey Work","Task Management","Workflow Execution"}, "Collaboration & Workflows",
			    IF(behavior IN {"Agent: Sales & Customer","Agent: IT & Service Desk","Agent: HR & People","Agent: Compliance & Policy","Agent: Coaching","Agent: Coaching (URL)","Domain-Specific Agent","Cross-Org Agent"}, "Specialist Agents",
			    IF(cat = "Teams Q&A", "Teams Chat",
			    IF(cat = "M365 Chat Q&A", "BizChat Q&A",
			    IF(cat = "Browser Q&A", "BizChat Q&A",
			    "General Q&A"))))))))))))
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000096
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AppIdentity_AppId
		dataType: string
		lineageTag: 120264b3-d8cc-47e6-8d80-aa66d06d0e2d
		summarizeBy: none
		sourceColumn: AppIdentity_AppId

		annotation SummarizationSetBy = Automatic

	column AppIdentity_DisplayName
		dataType: string
		lineageTag: 6e5c1eae-fb67-4d5b-a812-c72269d13af2
		summarizeBy: none
		sourceColumn: AppIdentity_DisplayName

		annotation SummarizationSetBy = Automatic

	column ApplicationName
		dataType: string
		lineageTag: 039ae66d-de5e-413b-b647-5602bdecf338
		summarizeBy: none
		sourceColumn: ApplicationName

		annotation SummarizationSetBy = Automatic

	column Resource_Count
		dataType: int64
		formatString: 0
		lineageTag: 8d82c478-0b7f-4417-b2ce-6dd7eb7d973b
		summarizeBy: sum
		sourceColumn: Resource_Count

		annotation SummarizationSetBy = Automatic

	/// Date-only copy of InteractionDate used for the Calendar relationship (lower cardinality than raw datetime)
	column ActivityDate = 'Chat + Agent Interactions (Audit Logs)'[InteractionDate]
		dataType: dateTime
		formatString: General Date
		lineageTag: 23423086-31bb-4769-bba6-455d200862c5
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'License Status' =
			VAR LicenseVal = UPPER(TRIM('Chat + Agent Interactions (Audit Logs)'[Has license]))
			RETURN
			IF(
			    LicenseVal = "YES" || LicenseVal = "TRUE" || LicenseVal = "Y" || LicenseVal = "1",
			    "M365 Copilot Licensed",
			    "Unlicensed"
			)
		dataType: string
		lineageTag: a6863ae7-217a-49f5-805c-62ef4677c5d0
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Environment =
			VAR hasAgent = NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentName])) && 'Chat + Agent Interactions (Audit Logs)'[AgentName] <> ""
			VAR hasAgentId = NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AgentId])) && 'Chat + Agent Interactions (Audit Logs)'[AgentId] <> ""
			VAR appHost = LOWER('Chat + Agent Interactions (Audit Logs)'[AppHost])
			VAR license = UPPER(TRIM('Chat + Agent Interactions (Audit Logs)'[Has license]))
			RETURN
			    IF(appHost IN {"autonomous","logic app"}, "Autonomous Agent",
			    IF(CONTAINSSTRING(appHost, "cowork"), "Cowork",
			    IF(hasAgent || hasAgentId, "Agents",
			    IF(license IN {"YES","TRUE","Y","1"}, "Licensed M365 Copilot",
			    "Unlicensed Chat"))))
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000004
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Is_Sensitive =
			(NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[SensitivityLabelId])) && 'Chat + Agent Interactions (Audit Logs)'[SensitivityLabelId] <> "")
			|| (NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[AccessedResource_SensitivityLabelId])) && 'Chat + Agent Interactions (Audit Logs)'[AccessedResource_SensitivityLabelId] <> "")
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ff030001-0001-0001-0001-000000000006
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Human-readable AI model label based on ModelTransparencyDetails
	column AI_Model =
			VAR modelName = UPPER('Chat + Agent Interactions (Audit Logs)'[ModelTransparencyDetails_ModelName])
			RETURN
			    IF(ISBLANK(modelName) || modelName = "NULL" || modelName = "", "Embedded App (no model logged)",
			    IF(CONTAINSSTRING(modelName, "DEEP_LEO"), "GPT-4 (Standard)",
			    IF(CONTAINSSTRING(modelName, "REASONING"), "Reasoning Model (o1/o3)",
			    IF(CONTAINSSTRING(modelName, "OFFENSIVE"), "Safety Filter (blocked)",
			    IF(CONTAINSSTRING(modelName, "GPT-41") || CONTAINSSTRING(modelName, "GPT-4.1"), "GPT-4.1 (Next Gen)",
			    IF(CONTAINSSTRING(modelName, "O3-MINI") || CONTAINSSTRING(modelName, "O3MINI"), "o3-mini (Reasoning)",
			    IF(CONTAINSSTRING(modelName, "O3") || CONTAINSSTRING(modelName, "O1"), "Reasoning Model (o-series)",
			    IF(CONTAINSSTRING(modelName, "GPT-5") || CONTAINSSTRING(modelName, "GPT5"), "GPT-5 (Next Gen)",
			    IF(CONTAINSSTRING(modelName, "CLAUDE"), "Claude (Anthropic)",
			    IF(CONTAINSSTRING(modelName, "GEMINI"), "Gemini (Google)",
			    IF(CONTAINSSTRING(modelName, "LLAMA") || CONTAINSSTRING(modelName, "META"), "LLaMA (Meta)",
			    IF(CONTAINSSTRING(modelName, "PHI"), "Phi (Microsoft Small Model)",
			    modelName))))))))))))
		dataType: string
		lineageTag: ff030001-0001-0001-0001-000000000178
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Frontier Firm Autonomy Pattern. Single categorical column pairing with user % / hours measures. Derived from Environment.
	column Autonomy_Pattern =
			VAR env = 'Chat + Agent Interactions (Audit Logs)'[Environment]
			RETURN
			    IF(env = "Licensed M365 Copilot", "1 - Copilot",
			    IF(env = "Agents", "2 - Agent-Assisted",
			    IF(env = "Autonomous Agent", "3 - Autonomous",
			    BLANK())))
		dataType: string
		lineageTag: ff0d0001-0001-0001-0001-000000000010
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Composite key (UserId|YYYY-MM) for joining to UserMonthMetrics — computed in DAX, not M
	column UserMonthKey =
			'Chat + Agent Interactions (Audit Logs)'[Audit_UserId] & "|" &
			FORMAT('Chat + Agent Interactions (Audit Logs)'[MonthStart], "yyyy-MM")
		dataType: string
		isHidden
		lineageTag: ff030001-0001-0001-0001-000000000200
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ModelTransparencyDetails_ModelProviderName
		dataType: string
		lineageTag: df62650f-af1d-40ef-b7de-195d5e0e3bde
		summarizeBy: none
		sourceColumn: ModelTransparencyDetails_ModelProviderName

		annotation SummarizationSetBy = Automatic

	column Audit_UserKey
		dataType: string
		lineageTag: 6167a80e-3b05-4e7a-b8b3-473ceb37c757
		summarizeBy: none
		sourceColumn: Audit_UserKey

		annotation SummarizationSetBy = Automatic

	hierarchy 'Value_Outcome Hierarchy'
		lineageTag: 32c2c649-b74e-4956-bff7-559d24a67fd9

		level Value_Outcome
			lineageTag: 97e316e7-d38e-4173-bae1-33318dff2696
			column: Value_Outcome

		level Behavior
			lineageTag: c1d964dc-0f31-4e8e-b174-bc0b9fcd6e2d
			column: Behavior_Enriched_Full

	partition 'Chat + Agent Interactions (Audit Logs)' = m
		mode: import
		source =
				let
				    // Pre-parsed audit log: data is already JSON-parsed and fanned out to one row per
				    // (prompt x resource). No JSON parsing, ExpandRecordColumn or ExpandListColumn needed.
				    // Heavy work moved upstream (script / dataflow / Fabric pipeline).
				    // SharePoint URL only — local paths are deliberately not supported on this variant
				    // because they fail in Service refresh and the dual Web/File pattern can trigger
				    // Formula.Firewall during static analysis.
				    FilePath = #"Copilot Interactions File",
				    Source = Csv.Document(Web.Contents(FilePath), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				
				    // ---- Pre-parsed variant: adapts Alex's current export script ---------------------
				    // The script flattens top-level audit fields but keeps these as JSON-strings:
				    //   AccessedResources : JSON array of resource objects
				    //   AISystemPlugin    : JSON object (or array) of plugin metadata
				    // It also doesn't emit a few canonical columns. We synthesise / parse them here
				    // so downstream measures see the same shape as the pre-parsed canonical schema.
				    #"Add Message_isPrompt"        = Table.AddColumn(#"Promoted Headers",        "Message_isPrompt",                    each "TRUE", type text),
				    #"Add ApplicationName"         = Table.AddColumn(#"Add Message_isPrompt",     "ApplicationName",                     each null, type text),
				    #"Add Audit_UserKey"           = Table.AddColumn(#"Add ApplicationName",      "Audit_UserKey",                       each null, type text),
				    #"Add SensitivityLabelId"      = Table.AddColumn(#"Add Audit_UserKey",        "SensitivityLabelId",                  each null, type text),
				    #"Add AR_SensLabel"            = Table.AddColumn(#"Add SensitivityLabelId",   "AccessedResource_SensitivityLabelId", each null, type text),
				
				    // Split the flat AppIdentity column (always a string in this export) into _AppId / _DisplayName.
				    #"Add AppIdentity_AppId"       = Table.AddColumn(#"Add AR_SensLabel",          "AppIdentity_AppId",       each null, type text),
				    #"Add AppIdentity_DisplayName" = Table.AddColumn(#"Add AppIdentity_AppId",    "AppIdentity_DisplayName", each try Text.From([AppIdentity]) otherwise null, type text),
				    #"Drop AppIdentity"            = Table.RemoveColumns(#"Add AppIdentity_DisplayName", {"AppIdentity"}, MissingField.Ignore),
				
				    // Parse AccessedResources JSON-string and explode to one row per resource.
				    #"Parse AR" = Table.AddColumn(#"Drop AppIdentity", "_resources", each
				        let
				            raw    = [AccessedResources],
				            parsed = if raw = null or raw = "" then null else try Json.Document(raw) otherwise null,
				            asList = if parsed is list then parsed
				                     else if parsed is record then {parsed}
				                     else {[Type = null, Action = null, SiteUrl = null]},
				            safe   = if List.Count(asList) > 0 then asList else {[Type = null, Action = null, SiteUrl = null]}
				        in safe),
				    #"Drop AR Original" = Table.RemoveColumns(#"Parse AR", {"AccessedResources"}, MissingField.Ignore),
				    #"Expand AR Rows"   = Table.ExpandListColumn(#"Drop AR Original", "_resources"),
				    #"Expand AR Cols"   = Table.ExpandRecordColumn(#"Expand AR Rows", "_resources",
				        {"Type", "Action", "SiteUrl"},
				        {"AccessedResource_Type", "AccessedResource_Action", "AccessedResource_SiteUrl"}),
				
				    // Parse AISystemPlugin JSON-string. Handle both single-object and array forms.
				    #"Parse Plugin" = Table.AddColumn(#"Expand AR Cols", "_plugin", each
				        let
				            raw    = [AISystemPlugin],
				            parsed = if raw = null or raw = "" then null else try Json.Document(raw) otherwise null,
				            single = if parsed is list and List.Count(parsed) > 0 then parsed{0}
				                     else if parsed is record then parsed
				                     else [Id = null, Name = null]
				        in single),
				    #"Drop Plugin Original" = Table.RemoveColumns(#"Parse Plugin", {"AISystemPlugin"}, MissingField.Ignore),
				    #"Expand Plugin"        = Table.ExpandRecordColumn(#"Drop Plugin Original", "_plugin",
				        {"Id", "Name"},
				        {"AISystemPlugin_Id", "AISystemPlugin_Name"}),
				    // ---- end Pre-parsed variant adaptations ----------------------------------------
				
				    // Type CreationDate (ISO-8601) explicitly with en-US culture for locale safety.
				    #"Typed CreationDate" = Table.TransformColumnTypes(#"Expand Plugin", {{"CreationDate", type datetime}}, "en-US"),
				
				    // Recompute date-derived columns from typed CreationDate (don't trust DD/MM text formats).
				    #"Drop Existing Date Cols" = Table.RemoveColumns(#"Typed CreationDate", {"InteractionDate", "WeekStart", "MonthStart"}, MissingField.Ignore),
				    #"Add InteractionDate" = Table.AddColumn(#"Drop Existing Date Cols", "InteractionDate", each try DateTime.Date([CreationDate]) otherwise null, type date),
				    #"Add WeekStart" = Table.AddColumn(#"Add InteractionDate", "WeekStart", each try Date.StartOfWeek([InteractionDate], Day.Monday) otherwise null, type date),
				    #"Add MonthStart" = Table.AddColumn(#"Add WeekStart", "MonthStart", each try Date.StartOfMonth([InteractionDate]) otherwise null, type date),
				
				    // Resource_Count: preserve from the parsed CSV if present (real per-event fan-out count),
				    // otherwise default each row to 1 (data assumed already fanned out at row level).
				    #"Add Resource Count" =
				        if Table.HasColumns(#"Add MonthStart", "Resource_Count")
				        then Table.TransformColumnTypes(#"Add MonthStart", {{"Resource_Count", Int64.Type}})
				        else Table.AddColumn(#"Add MonthStart", "Resource_Count", each 1, Int64.Type),
				
				    // Normalise UPN for the licensed-user merge if not already provided.
				    #"Normalize UPN" = Table.AddColumn(#"Add Resource Count", "_NormUPN", each
				        if Table.HasColumns(#"Add Resource Count", "Audit_UserId_Normalized")
				        then [Audit_UserId_Normalized]
				        else try Text.Lower(Text.Trim(Text.From([Audit_UserId]))) otherwise null,
				        type text),
				
				    // Merge Copilot Licenses info (LeftOuter so missing licenses don't drop rows).
				    #"Merged Licenses" = Table.NestedJoin(#"Normalize UPN", {"_NormUPN"}, #"Copilot Licensed", {"UPN_Normalized"}, "LicenseInfo", JoinKind.LeftOuter),
				    #"Expanded License" = Table.ExpandTableColumn(#"Merged Licenses", "LicenseInfo", {"Has license"}, {"Has license"}),
				
				    #"Final" = Table.RemoveColumns(#"Expanded License", {"_NormUPN", "Audit_UserId_Normalized"}, MissingField.Ignore)
				in
				    #"Final"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

