table 'Copilot Licensed'
	lineageTag: d2642023-4b65-422e-b87e-2db288a27359

	/// Total licensed users count (deduped on UPN_Normalized).
	/// Re-used by Inactive Licensed Users + Licensed Utilisation %.
	measure 'Total Licensed Users' =
			CALCULATE(
			    DISTINCTCOUNT('Copilot Licensed'[UPN_Normalized]),
			    UPPER(TRIM('Copilot Licensed'[Has license])) IN {"YES","TRUE","Y","1"}
			)
		formatString: #,##0
		displayFolder: License Readiness
		lineageTag: cc010001-0001-0001-0001-000000000001

	/// Licensed users with no prompts in the audit log (in current filter context).
	/// Subtracts the active-licensed user count from the total licence list — so
	/// "inactive" respects whatever date / org slicer is in effect.
	measure 'Inactive Licensed Users' =
			VAR LicensedTotal = [Total Licensed Users]
			VAR LicensedActive = [NoOfActiveChatUsers (Licensed)]
			RETURN
			    LicensedTotal - LicensedActive
		formatString: #,##0
		displayFolder: License Readiness
		lineageTag: cc010001-0001-0001-0001-000000000002

	/// Licensed utilisation: % of licensed users who are active in current filter context.
	measure 'Licensed Utilisation %' =
			DIVIDE(
			    [NoOfActiveChatUsers (Licensed)],
			    [Total Licensed Users],
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: License Readiness
		lineageTag: cc010001-0001-0001-0001-000000000003

	column 'User Principal Name'
		dataType: string
		lineageTag: 272d6b1b-4f26-4fcf-aedf-0b0bbbbe42a7
		summarizeBy: none
		sourceColumn: User Principal Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Has license'
		dataType: string
		lineageTag: 71a5d25c-0ad3-4d0c-abf2-f2f75725fe21
		summarizeBy: none
		sourceColumn: Has license

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPN_Normalized
		dataType: string
		lineageTag: d34e7c05-021e-4f79-96db-dce2199ce840
		summarizeBy: none
		sourceColumn: UPN_Normalized

		annotation SummarizationSetBy = Automatic

	column 'Report Refresh Date'
		dataType: string
		lineageTag: 41c99dd1-7688-4a3a-a427-f673186c4325
		summarizeBy: none
		sourceColumn: Report Refresh Date

		annotation SummarizationSetBy = Automatic

	partition 'Copilot Licensed' = m
		mode: import
		source =
				let
				    // SharePoint URL only — local paths are deliberately not supported on this variant.
				    FilePath = #"Copilot Licensed Users",
				    Source2 = Csv.Document(
				        Web.Contents(FilePath),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				
				    #"Promoted Headers" = Table.PromoteHeaders(Source2, [PromoteAllScalars = true]),
				
				    // List accepted variants for User Principal Name
				    userPrincipalNameVariants = {"User Principal Name", "userPrincipalName", "UserPrincipalName", "User principal name"},
				    actualUPNColumn = List.First(List.Intersect({userPrincipalNameVariants, Table.ColumnNames(#"Promoted Headers")}), null),
				
				    // List accepted variants for Has License
				    hasLicenseVariants = {
				        "Has license",
				        "Has License",
				        "HasLicense",
				        "Has Copilot License",
				        "Has Copilot license",
				        "HasCopilotLicense",
				        "Has Copilot License Assigned",
				        "Has Copilot license assigned",
				        "isUser"
				    },
				    actualHasLicenseColumn = List.First(List.Intersect({hasLicenseVariants, Table.ColumnNames(#"Promoted Headers")}), null),
				
				    // Add missing columns with defaults if not found, then rename
				    #"With UPN" = if actualUPNColumn <> null then
				            #"Promoted Headers"
				        else
				            Table.AddColumn(#"Promoted Headers", "User Principal Name", each null, type text),
				
				    #"With License" = if actualHasLicenseColumn <> null then
				            #"With UPN"
				        else
				            Table.AddColumn(#"With UPN", "Has license", each "Unknown", type text),
				
				    #"Renamed Columns" =
				        Table.RenameColumns(
				            #"With License",
				            List.Combine({
				                if actualUPNColumn <> null and actualUPNColumn <> "User Principal Name" then {{actualUPNColumn, "User Principal Name"}} else {},
				                if actualHasLicenseColumn <> null and actualHasLicenseColumn <> "Has license" then {{actualHasLicenseColumn, "Has license"}} else {}
				            }),
				            MissingField.Ignore
				        ),
				
				    // Add a normalized join key (case-insensitive match helper)
				    #"Added UPN Normalized" =
				        Table.AddColumn(
				            #"Renamed Columns",
				            "UPN_Normalized",
				            each
				                let v = [User Principal Name]
				                in if v = null then null else Text.Lower(Text.Trim(Text.From(v))),
				            type text
				        ),
				
				    // Remove duplicates using the normalized key
				    #"Removed Duplicates" = Table.Distinct(#"Added UPN Normalized", {"UPN_Normalized"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

