table Headlines
	isHidden
	lineageTag: ff0a0001-0001-0001-0001-000000000001

	/// Executive summary headline
	measure 'Executive Headline' =
			"AI performed " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([AI Tasks], "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			" tasks — saving " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([Efficiency - Hours Per Week], "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			" hours per week, creating " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([Work Created - Per Week], "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			" work items, and unlocking " &
			SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([New Expertise - Roles], "0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " specialist roles."
		displayFolder: Headlines
		lineageTag: ff0a0001-0001-0001-0001-000000000010

	/// Usage Mode headline
	measure 'Usage Mode Headline' =
			VAR ProdRate = [Productive AI Rate]
			VAR AutoRate = [Automating AI Rate]
			RETURN
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(ProdRate, "0%"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " of AI usage is Producing (creating deliverables or specialist work), " &
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(AutoRate, "0%"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " is Automating (workflow execution and autonomous agents). " &
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([New Expertise - Users], "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " users access specialist AI expertise."
		displayFolder: Headlines
		lineageTag: ff0a0001-0001-0001-0001-000000000018

	/// User Maturity - By Organisation bookmark
	measure 'Maturity By Org Headline' =
			VAR TotalOrgs = DISTINCTCOUNT('Chat + Agent Org Data'[Organization])
			VAR OrgsWithProficient = CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Org Data'[Organization]),
			    'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "3 - Proficient"
			)
			RETURN
			    "User maturity across " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(TotalOrgs, "0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " organisations — " &
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(OrgsWithProficient, "0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " have Proficient users. " &
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([Proficient Users %], "0%"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " of all users have reached Proficient stage."
		displayFolder: Headlines\Maturity
		lineageTag: ff0a0001-0001-0001-0001-000000000023

	/// User Maturity - Task Breakdown bookmark
	measure 'Maturity Task Breakdown Headline' =
			VAR BegAvg = AVERAGEX(
			    CALCULATETABLE(VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "1 - Beginner"),
			    CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Efficiency_Breakdown]))
			)
			VAR ProAvg = AVERAGEX(
			    CALCULATETABLE(VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "3 - Proficient"),
			    CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Efficiency_Breakdown]))
			)
			RETURN
			    "What tasks is AI doing at each stage? " &
			    "Beginners average " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(BegAvg, "0.0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " task types, " &
			    "Proficient users average " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(ProAvg, "0.0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " — " &
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(DIVIDE(ProAvg, BegAvg, 0), "0.0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & "x the breadth."
		displayFolder: Headlines\Maturity
		lineageTag: ff0a0001-0001-0001-0001-000000000025

	/// User Maturity - Specialist Roles bookmark
	measure 'Maturity Specialist Headline' =
			VAR BegRoles = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "1 - Beginner", NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR DevRoles = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "2 - Developing", NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR ProRoles = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "3 - Proficient", NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR ProTotal = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "3 - Proficient")
			VAR ProExpertUsers = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "3 - Proficient", NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR ProExpertPct = DIVIDE(ProExpertUsers, ProTotal, 0)
			RETURN
			    "What specialist roles is AI unlocking? " &
			    "Beginners access " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(BegRoles, "0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " roles, " &
			    "Developing " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(DevRoles, "0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & ", " &
			    "Proficient " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(ProRoles, "0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & ". " &
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(ProExpertPct, "0%"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " of Proficient users leverage specialist AI expertise."
		displayFolder: Headlines\Maturity
		lineageTag: ff0a0001-0001-0001-0001-000000000026

	/// Efficiency only headline (for Time Saved bookmarks)
	measure 'Efficiency Headline' =
			VAR HrsPerWeek = [Efficiency - Hours Per Week]
			VAR Users = DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId])
			VAR TopArea = MAXX(TOPN(1, ADDCOLUMNS(VALUES('Chat + Agent Interactions (Audit Logs)'[Efficiency_Breakdown]), "@Hrs", [Human Equivalent Hours]), [@Hrs], DESC), 'Chat + Agent Interactions (Audit Logs)'[Efficiency_Breakdown])
			RETURN
			    "AI saved " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(HrsPerWeek, "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			    " hours per week across " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(Users, "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			    " users (" & [Efficiency - Label] & " per user). Most time saved in " & TopArea & "."
		displayFolder: Headlines
		lineageTag: ff0a0001-0001-0001-0001-000000000027

	/// Copilot Value - Augmented Skills bookmark
	measure 'Copilot Skills Headline' =
			"Copilot users access " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([Avg Skills Per User], "#,##0.0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			" AI-augmented skill types on average — from email drafting to data analysis."
		displayFolder: Headlines\Copilot Value
		lineageTag: ff0a0001-0001-0001-0001-000000000031

	/// Agent Value - Augmented Skills bookmark
	measure 'Agent Skills Headline' =
			"Agents unlock specialist capabilities: " &
			SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([New Expertise - Roles], "0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " expert roles accessed by " &
			SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([New Expertise - Users], "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") & " users."
		displayFolder: Headlines\Agent Value
		lineageTag: ff0a0001-0001-0001-0001-000000000035

	/// Trend Heatmap page headline
	measure 'Heatmap Headline' =
			"Tracking " & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([All Active Users], "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			" active users across " &
			SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(DISTINCTCOUNT('Chat + Agent Org Data'[Organization]), "0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			" organisations — " & [Efficiency - Label] & " saved per user per week."
		displayFolder: Headlines
		lineageTag: ff0a0001-0001-0001-0001-000000000019

	/// License Readiness / Priority Ranking page headline
	measure 'License Priority Headline' =
			VAR UnlUsers = [NoOfActiveChatUsers (Unlicensed)]
			VAR UnlOrgs = CALCULATE(
			    DISTINCTCOUNT('Chat + Agent Org Data'[Organization]),
			    'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed"
			)
			VAR UnlTasksPUPW = [Unlicensed AI Tasks Per User Per Week]
			RETURN
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(UnlUsers, "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			    " unlicensed users across " &
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(UnlOrgs, "#,##0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			    " organisations are generating " &
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(UnlTasksPUPW, "#,##0.0"),"0","𝟎"),"1","𝟏"),"2","𝟐"),"3","𝟑"),"4","𝟒"),"5","𝟓"),"6","𝟔"),"7","𝟕"),"8","𝟖"),"9","𝟗") &
			    " AI tasks/user/week — ranked candidates for M365 Copilot licensing."
		displayFolder: Headlines\License
		lineageTag: ff0a0001-0001-0001-0001-000000000040

	column Placeholder
		lineageTag: 6dd949b7-b523-4a00-be54-69752cc60699
		isNameInferred
		sourceColumn: [Placeholder]

	partition Headlines = calculated
		mode: import
		source = ROW("Placeholder", 1)

