table 'Hourly Value'
	lineageTag: a3052c25-d454-4528-8be1-9b2c3b4bbfa8

	measure 'Hourly Value Value' = SELECTEDVALUE('Hourly Value'[Hourly Value], 50)
		formatString: 0
		lineageTag: 91a18172-c596-4293-a9f1-c628aa5015f2

	column 'Hourly Value'
		formatString: 0
		lineageTag: 9388c68f-de92-43ac-98c7-afd2547dd4a8
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Hourly Value' = calculated
		mode: import
		source = GENERATESERIES(0, 1000, 1)

	annotation PBI_Id = 50197f65537441b294321d2441bc4c74

