table 'Human Time Estimates'
	lineageTag: ff060001-0001-0001-0001-000000000001

	column Behavior
		dataType: string
		lineageTag: ff060001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: Behavior

		annotation SummarizationSetBy = Automatic

	column 'Human Baseline (min)'
		dataType: int64
		lineageTag: ff060001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Human Baseline (min)

		annotation SummarizationSetBy = Automatic

	column 'Primary Source'
		dataType: string
		lineageTag: ff060001-0001-0001-0001-000000000005
		summarizeBy: none
		sourceColumn: Primary Source

		annotation SummarizationSetBy = Automatic

	column Confidence
		dataType: string
		lineageTag: 5e47e248-fc1d-4610-8c33-59d6dc02b0d1
		summarizeBy: none
		sourceColumn: Confidence

		annotation SummarizationSetBy = Automatic

	column 'Value Outcome'
		dataType: string
		lineageTag: e42da065-9ada-4d14-bc83-f7fd763c6977
		summarizeBy: none
		sourceColumn: Value Outcome

		annotation SummarizationSetBy = Automatic

	partition 'Human Time Estimates' = m
		mode: import
		source =
				let
				    Source = #table(
				        {"Behavior", "Human Baseline (min)", "Confidence", "Primary Source", "Value Outcome"},
				        {
				            // TIME SAVED (EMAIL)
				            {"Email Triage", 10, "Medium-High", "Microsoft Research (Iqbal & Horvitz 2007); McKinsey 2023", "Time Saved (Email)"},
				            {"Email Thread Summary", 5, "Medium", "Nielsen Norman Group 2023; Microsoft WTI 2024", "Time Saved (Email)"},
				            {"Email Summarising", 4, "Medium", "Dabbish & Kraut (CMU 2006); Mark et al. 2012", "Time Saved (Email)"},
				            // CONTENT CREATION
				            {"Email Drafting", 8, "High", "McKinsey 2023; Brynjolfsson et al. (NBER 2023)", "Content Output"},
				            {"Document Drafting", 60, "High", "Noy & Zhang (MIT/Science 2023); BCG/Harvard 2023", "Content Output"},
				            {"Presentation Creation", 90, "Medium-High", "Gartner 2024; BCG 2024", "Content Output"},
				            // TIME SAVED (MEETINGS)
				            {"Meeting Prep", 15, "High", "Forrester TEI 2024; HBR (Rogelberg 2019)", "Time Saved (Meetings)"},
				            {"Video Summarising", 30, "Medium-High", "Microsoft WTI 2024; Kaltura 2023", "Time Saved (Meetings)"},
				            // TIME SAVED (DOCUMENTS)
				            {"Document Summarising", 20, "Medium-High", "BCG/Harvard (Dell'Acqua et al. 2023); McKinsey 2023", "Time Saved (Documents)"},
				            {"Presentation Summarising", 12, "Medium", "Forrester TEI 2024; NNGroup 2020", "Time Saved (Documents)"},
				            // FASTER INFORMATION FINDING
				            {"Web Searching", 22, "High", "McKinsey (2012); IDC (2018)", "Search Time Saved"},
				            {"Enterprise Searching", 18, "High", "IDC (2014); McKinsey (2012)", "Search Time Saved"},
				            {"PDF Analysis", 35, "Medium", "Deloitte (2018); Thomson Reuters (2019)", "Search Time Saved"},
				            {"SharePoint Access", 12, "Medium", "Forrester TEI (2022); AIIM (2019)", "Search Time Saved"},
				            {"File Retrieval", 15, "Medium", "IDC (2014); McKinsey (2012)", "Search Time Saved"},
				            // DATA-DRIVEN DECISIONS
				            {"Data Querying", 30, "High", "Forrester TEI (2022); BCG (2021)", "Data-Driven Decisions"},
				            {"Spreadsheet Analysis", 40, "High", "Deloitte (2023); KPMG (2020)", "Data-Driven Decisions"},
				            // BETTER COMMUNICATION
				            {"Teams Messaging", 8, "Medium", "Microsoft WTI (2023); Grammarly (2023)", "Communication Time Saved"},
				            {"Meeting Scheduling", 12, "High", "Doodle (2019); HBR (2017)", "Communication Time Saved"},
				            // SKILLS DEVELOPMENT
				            {"Agent: Coaching", 45, "Medium", "ICF (2020); SHRM (2023)", "Skills Development"},
				            {"Agent: Coaching (URL)", 25, "Medium", "LinkedIn Learning (2023); Deloitte (2022)", "Skills Development"},
				            // REVENUE ENABLEMENT
				            {"Agent: Sales & Customer", 35, "High", "Salesforce (2023); Gartner (2022)", "Revenue Enablement"},
				            // SERVICE DESK DEFLECTION
				            {"Agent: IT & Service Desk", 20, "High", "HDI (2023); MetricNet (2023)", "Service Desk Deflection"},
				            // COMPLIANCE & TRUST
				            {"Agent: Compliance & Policy", 25, "Medium", "Deloitte (2022); Thomson Reuters (2023)", "Compliance & Risk"},
				            {"Sensitive Content Interaction", 20, "Low", "Deloitte (2023); Gartner (2022)", "Compliance & Risk"},
				            // TECHNICAL CAPABILITY
				            {"Code Writing", 45, "High", "GitHub/NBER (Peng et al. 2023) RCT", "Coding Capability"},
				            {"Code Analysis", 30, "High", "SmartBear (2023); MS Research (Bacchelli & Bird 2013)", "Coding Capability"},
				            {"Code Analysis (URL)", 15, "Medium", "Stack Overflow (2023); GitHub (2023)", "Coding Capability"},
				            // CONTENT CREATION (visual)
				            {"Image Generation", 60, "Medium", "Adobe (2022); Content Marketing Institute (2023)", "Content Output"},
				            {"Image/Media Analysis", 8, "Medium", "W3C WAI; DAM Institute (2022)", "Content Output"},
				            {"Image / Media Analysis", 8, "Medium", "W3C WAI; DAM Institute (2022)", "Content Output"},
				            // PEOPLE & ORG INTELLIGENCE
				            {"People Lookup", 10, "Medium", "Gartner (2021); Microsoft Viva (2022)", "Search Time Saved"},
				            // WORKFLOW AUTOMATION
				            {"Workflow Execution", 15, "High", "Forrester TEI (2022); Gartner (2023)", "Workflow Triggered"},
				            // TASK & PROJECT MANAGEMENT
				            {"Task Management", 20, "Medium", "Atlassian (2022); Scrum Alliance (2023)", "Task Coordination"},
				            // HR OPERATIONS
				            {"Agent: HR & People", 35, "High", "SHRM (2023); Deloitte (2023)", "HR Process Automation"},
				            // COLLABORATION & KNOWLEDGE
				            {"Real-time Collaboration", 30, "Medium", "Microsoft WTI (2023); Gartner (2022)", "Team Collaboration"},
				            {"Note Taking", 20, "High", "Microsoft Research (Branham & Brush 2015)", "Time Saved (Documents)"},
				            {"Form/Survey Work", 25, "Medium", "SurveyMonkey (2022); Qualtrics (2023)", "Team Collaboration"},
				            // DATA-DRIVEN DECISIONS (agents)
				            {"Agent: Research & Analysis", 45, "High", "BCG (2021); McKinsey (2023)", "Data-Driven Decisions"},
				            {"Agent: Data & Reporting", 35, "High", "Forrester TEI (2022); IDC (2023)", "Data-Driven Decisions"},
				            // CONTENT CREATION (agents)
				            {"Agent: Content Generation", 25, "High", "Grammarly (2023); Forrester (2022)", "Content Output"},
				            {"Agent: Ideation & Creative", 40, "Medium", "IDEO; HBR (2018)", "Content Output"},
				            // FASTER INFORMATION FINDING (agents)
				            {"Agent: Knowledge Base", 12, "High", "HDI (2023); Gartner (2022)", "Search Time Saved"},
				            // GENERAL AI ASSISTANCE
				            {"Agent: General Purpose", 15, "Low", "Microsoft WTI (2023); IDC (2023)", "General AI Productivity"},
				            {"M365 Chat Q&A", 10, "Medium", "Microsoft WTI (2023); IDC (2018)", "General AI Productivity"},
				            {"Teams Q&A", 10, "Medium", "Microsoft WTI (2023); IDC (2018)", "General AI Productivity"},
				            {"Browser Q&A", 10, "Medium", "Microsoft WTI (2023); IDC (2018)", "General AI Productivity"},
				            {"General Q&A", 10, "Medium", "Microsoft WTI (2023); IDC (2018)", "General AI Productivity"},
				            {"General Chat", 10, "Medium", "Microsoft WTI (2023); IDC (2018)", "General AI Productivity"},
				            // DOMAIN EXPERTISE
				            {"Domain-Specific Agent", 25, "Low", "Deloitte (2022); Gartner (2023)", "Specialist Expertise"},
				            {"Cross-Org Agent", 30, "Low", "McKinsey (2022); Forrester (2023)", "Specialist Expertise"},
				            // SPREADSHEET REVIEW / EXCEL ASSISTANCE — baselines aligned with Spreadsheet Analysis (40m) tier
				            {"Spreadsheet Review", 25, "Medium", "Deloitte (2023); KPMG (2020)", "Spreadsheet Time Saved"},
				            {"Excel Assistance", 30, "Medium", "Deloitte (2023); KPMG (2020)", "Spreadsheet Time Saved"},
				            // FORM / SURVEY WORK — alias of "Form/Survey Work" with spaces (matches Behavior_Enriched_Full output)
				            {"Form / Survey Work", 25, "Medium", "SurveyMonkey (2022); Qualtrics (2023)", "Team Collaboration"}
				        }
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {
				        {"Behavior", type text},
				        {"Human Baseline (min)", Int64.Type},
				        {"Confidence", type text},
				        {"Primary Source", type text},
				        {"Value Outcome", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

