table 'Penalty Factor'
	lineageTag: 5eab112b-6609-4777-827c-9d81022d016b

	measure 'Penalty Factor Value' = SELECTEDVALUE('Penalty Factor'[Penalty Factor], 1)
		lineageTag: 5e655404-411a-4f53-85c0-2e3a711cf798

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Penalty Factor'
		lineageTag: ecfe8672-ffd6-4801-8d19-a908cc765a92
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Penalty Factor' = calculated
		mode: import
		source = GENERATESERIES(0, 1.05, 0.05)

	annotation PBI_Id = f03c3fb597d641faac130a914d285a14

