/// Task-level value mapping. Each AI task (Behavior_Category) maps to a defensible work archetype and task-generic success metrics (Usage / KPI Impact / Workflow Automation). No inferred scenario attribution. Source: Microsoft Frontier Firm success-metric framework (2025), applied at task level.
table 'Task Value Mapping'
	lineageTag: ff0c0001-0001-0001-0001-000000000030

	column TaskBehavior
		dataType: string
		lineageTag: ff0c0001-0001-0001-0001-000000000031
		summarizeBy: none
		sourceColumn: TaskBehavior

		annotation SummarizationSetBy = Automatic

	column WorkArchetype
		dataType: string
		lineageTag: ff0c0001-0001-0001-0001-000000000032
		summarizeBy: none
		sourceColumn: WorkArchetype

		annotation SummarizationSetBy = Automatic

	column SuccessMetric
		dataType: string
		lineageTag: 6c8a3a49-f61c-46c2-a056-33038e4f346a
		summarizeBy: none
		sourceColumn: SuccessMetric

		annotation SummarizationSetBy = Automatic

	column SuccessMetricClass
		dataType: string
		lineageTag: e85203d9-9e4f-4b3e-91aa-761d1d4c18ea
		summarizeBy: none
		sourceColumn: SuccessMetricClass

		annotation SummarizationSetBy = Automatic

	column SuccessMetricShort
		dataType: string
		lineageTag: e4538120-3f24-4c1a-b5b4-50348cd1fbbe
		summarizeBy: none
		sourceColumn: SuccessMetricShort

		annotation SummarizationSetBy = Automatic

	partition 'Task Value Mapping' = m
		mode: import
		source =
				let
				    Source = #table(
				        {"TaskBehavior", "WorkArchetype", "SuccessMetric", "SuccessMetricClass", "SuccessMetricShort"},
				        {
				            // ============ CONTENT CREATION ============
				            {"Email Drafting", "Content Creation", "Reduction in time: Drafting written responses", "Usage", "Email draft time saved"},
				            {"Email Drafting", "Content Creation", "Throughput: Messages drafted with AI assistance", "KPI Impact", "Emails drafted"},
				            {"Email Drafting", "Content Creation", "% of drafts sent without manual edit", "Workflow Automation", "% emails auto-drafted"},
				
				            {"Document Drafting", "Content Creation", "Reduction in time: Drafting written content", "Usage", "Doc draft time saved"},
				            {"Document Drafting", "Content Creation", "Throughput: Documents produced with AI", "KPI Impact", "Docs produced"},
				            {"Document Drafting", "Content Creation", "% of documents produced end-to-end by AI", "Workflow Automation", "% docs auto-drafted"},
				
				            {"Presentation Creation", "Content Creation", "Reduction in time: Slide deck creation", "Usage", "Deck creation time saved"},
				            {"Presentation Creation", "Content Creation", "Throughput: Presentations produced", "KPI Impact", "Decks produced"},
				            {"Presentation Creation", "Content Creation", "% of decks generated without manual build", "Workflow Automation", "% decks auto-built"},
				
				            {"Image Generation", "Content Creation", "Reduction in time: Visual asset production", "Usage", "Asset creation time saved"},
				            {"Image Generation", "Content Creation", "Throughput: Visual assets produced", "KPI Impact", "Assets produced"},
				            {"Image Generation", "Content Creation", "% of visual assets produced autonomously", "Workflow Automation", "% assets auto-generated"},
				
				            {"Agent: Content Generation", "Content Creation", "Reduction in time: Content production cycles", "Usage", "Content time saved"},
				            {"Agent: Content Generation", "Content Creation", "Throughput: Content items produced by agent", "KPI Impact", "Items produced"},
				            {"Agent: Content Generation", "Content Creation", "% of content produced end-to-end by agent", "Workflow Automation", "% content auto-produced"},
				
				            {"Agent: Ideation & Creative", "Content Creation", "Reduction in time: Creative ideation cycles", "Usage", "Ideation time saved"},
				            {"Agent: Ideation & Creative", "Content Creation", "Volume of ideas / variations produced", "KPI Impact", "Ideas produced"},
				            {"Agent: Ideation & Creative", "Content Creation", "% of creative work produced autonomously", "Workflow Automation", "% creative autonomous"},
				
				            // ============ CONTENT CONSUMPTION ============
				            {"Email Summarising", "Content Consumption", "Reduction in time: Reading email threads", "Usage", "Email read time saved"},
				            {"Email Summarising", "Content Consumption", "Volume of messages consumed with AI summary", "KPI Impact", "Emails summarised"},
				            {"Email Summarising", "Content Consumption", "% of inbox triaged via AI summaries", "Workflow Automation", "% inbox auto-triaged"},
				
				            {"Email Thread Summary", "Content Consumption", "Reduction in time: Reading email threads", "Usage", "Thread read time saved"},
				            {"Email Thread Summary", "Content Consumption", "Volume of threads summarised", "KPI Impact", "Threads summarised"},
				            {"Email Thread Summary", "Content Consumption", "% of threads triaged via AI summaries", "Workflow Automation", "% threads auto-triaged"},
				
				            {"Email Triage", "Content Consumption", "Reduction in time: Inbox triage", "Usage", "Triage time saved"},
				            {"Email Triage", "Content Consumption", "Volume of messages triaged with AI", "KPI Impact", "Emails triaged"},
				            {"Email Triage", "Content Consumption", "% of inbox triaged autonomously", "Workflow Automation", "% inbox auto-triaged"},
				
				            {"Document Summarising", "Content Consumption", "Reduction in time: Reading documents", "Usage", "Doc read time saved"},
				            {"Document Summarising", "Content Consumption", "Volume of documents summarised", "KPI Impact", "Docs summarised"},
				            {"Document Summarising", "Content Consumption", "% of documents consumed via AI summary", "Workflow Automation", "% docs auto-summarised"},
				
				            {"Presentation Summarising", "Content Consumption", "Reduction in time: Consuming presentations", "Usage", "Deck read time saved"},
				            {"Presentation Summarising", "Content Consumption", "Volume of presentations summarised", "KPI Impact", "Decks summarised"},
				            {"Presentation Summarising", "Content Consumption", "% of decks consumed via AI summary", "Workflow Automation", "% decks auto-summarised"},
				
				            {"PDF Analysis", "Content Consumption", "Reduction in time: Reading PDF documents", "Usage", "PDF read time saved"},
				            {"PDF Analysis", "Content Consumption", "Volume of PDFs analysed", "KPI Impact", "PDFs analysed"},
				            {"PDF Analysis", "Content Consumption", "% of PDF review handled autonomously", "Workflow Automation", "% PDFs auto-analysed"},
				
				            {"Video Summarising", "Content Consumption", "Reduction in time: Consuming video / recordings", "Usage", "Video time saved"},
				            {"Video Summarising", "Content Consumption", "Volume of recordings summarised", "KPI Impact", "Recordings summarised"},
				            {"Video Summarising", "Content Consumption", "% of recordings consumed via AI summary", "Workflow Automation", "% recordings auto-summarised"},
				
				            {"Image / Media Analysis", "Content Consumption", "Reduction in time: Visual content analysis", "Usage", "Media analysis time saved"},
				            {"Image / Media Analysis", "Content Consumption", "Volume of images / media analysed", "KPI Impact", "Media analysed"},
				            {"Image / Media Analysis", "Content Consumption", "% of media analysis automated", "Workflow Automation", "% media auto-analysed"},
				
				            // ============ SEARCH & RETRIEVAL ============
				            {"Web Searching", "Search & Retrieval", "Reduction in time: Finding external information", "Usage", "Web search time saved"},
				            {"Web Searching", "Search & Retrieval", "Volume of web research queries resolved", "KPI Impact", "Web queries resolved"},
				            {"Web Searching", "Search & Retrieval", "% of research handled via AI-grounded search", "Workflow Automation", "% research AI-grounded"},
				
				            {"Enterprise Searching", "Search & Retrieval", "Reduction in time: Finding internal information", "Usage", "Internal search time saved"},
				            {"Enterprise Searching", "Search & Retrieval", "Volume of enterprise searches resolved", "KPI Impact", "Enterprise queries resolved"},
				            {"Enterprise Searching", "Search & Retrieval", "% of knowledge lookup handled autonomously", "Workflow Automation", "% lookup autonomous"},
				
				            {"File Retrieval", "Search & Retrieval", "Reduction in time: Locating files", "Usage", "File-find time saved"},
				            {"File Retrieval", "Search & Retrieval", "Volume of file retrieval requests", "KPI Impact", "Files retrieved"},
				            {"File Retrieval", "Search & Retrieval", "% of file retrieval automated", "Workflow Automation", "% file-find automated"},
				
				            {"SharePoint Access", "Search & Retrieval", "Reduction in time: Navigating SharePoint content", "Usage", "SharePoint time saved"},
				            {"SharePoint Access", "Search & Retrieval", "Volume of SharePoint lookups", "KPI Impact", "SharePoint lookups"},
				            {"SharePoint Access", "Search & Retrieval", "% of SharePoint access handled via AI", "Workflow Automation", "% SharePoint AI-assisted"},
				
				            {"People Lookup", "Search & Retrieval", "Reduction in time: Finding people / expertise", "Usage", "People-find time saved"},
				            {"People Lookup", "Search & Retrieval", "Volume of people lookups resolved", "KPI Impact", "People lookups"},
				            {"People Lookup", "Search & Retrieval", "% of expertise discovery automated", "Workflow Automation", "% people-find automated"},
				
				            {"Agent: Knowledge Base", "Search & Retrieval", "Reduction in time: Knowledge-base queries", "Usage", "KB query time saved"},
				            {"Agent: Knowledge Base", "Search & Retrieval", "Volume of knowledge queries answered by agent", "KPI Impact", "KB queries answered"},
				            {"Agent: Knowledge Base", "Search & Retrieval", "% of queries deflected to agent autonomously", "Workflow Automation", "% KB auto-deflected"},
				
				            // ============ ANALYSIS & DECISIONS ============
				            {"Data Querying", "Analysis & Decisions", "Reduction in time: Data querying", "Usage", "Data query time saved"},
				            {"Data Querying", "Analysis & Decisions", "Volume of queries answered with AI", "KPI Impact", "Data queries answered"},
				            {"Data Querying", "Analysis & Decisions", "% of data-access requests automated", "Workflow Automation", "% data-access automated"},
				
				            {"Spreadsheet Analysis", "Analysis & Decisions", "Reduction in time: Spreadsheet analysis", "Usage", "Analysis time saved"},
				            {"Spreadsheet Analysis", "Analysis & Decisions", "Volume of analyses completed with AI", "KPI Impact", "Analyses completed"},
				            {"Spreadsheet Analysis", "Analysis & Decisions", "% of analytical tasks handled autonomously", "Workflow Automation", "% analysis autonomous"},
				
				            {"Spreadsheet Review", "Analysis & Decisions", "Reduction in time: Reviewing spreadsheet content", "Usage", "Review time saved"},
				            {"Spreadsheet Review", "Analysis & Decisions", "Volume of spreadsheets reviewed with AI", "KPI Impact", "Spreadsheets reviewed"},
				            {"Spreadsheet Review", "Analysis & Decisions", "% of spreadsheet review automated", "Workflow Automation", "% review automated"},
				
				            {"Excel Assistance", "Analysis & Decisions", "Reduction in time: Excel tasks", "Usage", "Excel time saved"},
				            {"Excel Assistance", "Analysis & Decisions", "Volume of Excel operations AI-assisted", "KPI Impact", "Excel ops assisted"},
				            {"Excel Assistance", "Analysis & Decisions", "% of Excel work produced with AI", "Workflow Automation", "% Excel AI-assisted"},
				
				            {"Agent: Research & Analysis", "Analysis & Decisions", "Reduction in time: Research cycles", "Usage", "Research time saved"},
				            {"Agent: Research & Analysis", "Analysis & Decisions", "Volume of research deliverables produced", "KPI Impact", "Research produced"},
				            {"Agent: Research & Analysis", "Analysis & Decisions", "% of research handled end-to-end by agent", "Workflow Automation", "% research autonomous"},
				
				            {"Agent: Data & Reporting", "Analysis & Decisions", "Reduction in time: Reporting cycles", "Usage", "Reporting time saved"},
				            {"Agent: Data & Reporting", "Analysis & Decisions", "Volume of reports / dashboards produced", "KPI Impact", "Reports produced"},
				            {"Agent: Data & Reporting", "Analysis & Decisions", "% of reporting handled autonomously", "Workflow Automation", "% reporting autonomous"},
				
				            // ============ WORKFLOW AUTOMATION ============
				            {"Workflow Execution", "Workflow Automation", "Reduction in time: Manual workflow steps", "Usage", "Workflow time saved"},
				            {"Workflow Execution", "Workflow Automation", "Volume of workflow actions triggered", "KPI Impact", "Workflows triggered"},
				            {"Workflow Execution", "Workflow Automation", "% of end-to-end workflows handled autonomously", "Workflow Automation", "% workflows autonomous"},
				
				            {"Task Management", "Workflow Automation", "Reduction in time: Task coordination", "Usage", "Task coord time saved"},
				            {"Task Management", "Workflow Automation", "Volume of tasks managed with AI", "KPI Impact", "Tasks managed"},
				            {"Task Management", "Workflow Automation", "% of task management automated", "Workflow Automation", "% task mgmt automated"},
				
				            {"Meeting Scheduling", "Workflow Automation", "Reduction in time: Meeting coordination", "Usage", "Meeting coord time saved"},
				            {"Meeting Scheduling", "Workflow Automation", "Volume of meetings scheduled via AI", "KPI Impact", "Meetings scheduled"},
				            {"Meeting Scheduling", "Workflow Automation", "% of meeting logistics automated", "Workflow Automation", "% scheduling automated"},
				
				            {"Meeting Prep", "Workflow Automation", "Reduction in time: Pre-meeting preparation", "Usage", "Meeting prep time saved"},
				            {"Meeting Prep", "Workflow Automation", "Volume of meetings AI-prepared", "KPI Impact", "Meetings AI-prepared"},
				            {"Meeting Prep", "Workflow Automation", "% of meeting prep handled autonomously", "Workflow Automation", "% prep autonomous"},
				
				            {"Teams Messaging", "Workflow Automation", "Reduction in time: Team messaging", "Usage", "Messaging time saved"},
				            {"Teams Messaging", "Workflow Automation", "Volume of messages AI-assisted", "KPI Impact", "Messages AI-assisted"},
				            {"Teams Messaging", "Workflow Automation", "% of routine messaging automated", "Workflow Automation", "% messaging automated"},
				
				            {"Real-time Collaboration", "Workflow Automation", "Reduction in time: Collaborative work", "Usage", "Collab time saved"},
				            {"Real-time Collaboration", "Workflow Automation", "Volume of collaborative sessions AI-supported", "KPI Impact", "Collab sessions"},
				            {"Real-time Collaboration", "Workflow Automation", "% of collaboration automated", "Workflow Automation", "% collab automated"},
				
				            {"Form/Survey Work", "Workflow Automation", "Reduction in time: Form / survey handling", "Usage", "Form time saved"},
				            {"Form/Survey Work", "Workflow Automation", "Volume of form submissions AI-processed", "KPI Impact", "Forms processed"},
				            {"Form/Survey Work", "Workflow Automation", "% of form processing automated", "Workflow Automation", "% forms automated"},
				
				            {"Note Taking", "Workflow Automation", "Reduction in time: Note capture", "Usage", "Note-take time saved"},
				            {"Note Taking", "Workflow Automation", "Volume of sessions with AI notes", "KPI Impact", "Sessions noted"},
				            {"Note Taking", "Workflow Automation", "% of note-taking handled autonomously", "Workflow Automation", "% notes autonomous"},
				
				            // ============ ADVISORY & EXPERTISE ============
				            {"Agent: Coaching", "Advisory & Expertise", "Reduction in time: Seeking coaching / guidance", "Usage", "Coaching time saved"},
				            {"Agent: Coaching", "Advisory & Expertise", "Volume of coaching interactions", "KPI Impact", "Coaching interactions"},
				            {"Agent: Coaching", "Advisory & Expertise", "% of coaching delivered autonomously", "Workflow Automation", "% coaching autonomous"},
				
				            {"Agent: IT & Service Desk", "Advisory & Expertise", "Reduction in time: IT support interactions", "Usage", "IT support time saved"},
				            {"Agent: IT & Service Desk", "Advisory & Expertise", "Volume of IT tickets handled by agent", "KPI Impact", "IT tickets handled"},
				            {"Agent: IT & Service Desk", "Advisory & Expertise", "% of IT tickets resolved autonomously", "Workflow Automation", "% IT tickets autonomous"},
				
				            {"Agent: HR & People", "Advisory & Expertise", "Reduction in time: HR support interactions", "Usage", "HR support time saved"},
				            {"Agent: HR & People", "Advisory & Expertise", "Volume of HR queries handled by agent", "KPI Impact", "HR queries handled"},
				            {"Agent: HR & People", "Advisory & Expertise", "% of HR queries resolved autonomously", "Workflow Automation", "% HR queries autonomous"},
				
				            {"Agent: Sales & Customer", "Advisory & Expertise", "Reduction in time: Sales / customer interactions", "Usage", "Sales time saved"},
				            {"Agent: Sales & Customer", "Advisory & Expertise", "Volume of customer interactions handled by agent", "KPI Impact", "Customer interactions"},
				            {"Agent: Sales & Customer", "Advisory & Expertise", "% of customer interactions handled autonomously", "Workflow Automation", "% customer autonomous"},
				
				            {"Agent: Compliance & Policy", "Advisory & Expertise", "Reduction in time: Compliance / policy queries", "Usage", "Compliance time saved"},
				            {"Agent: Compliance & Policy", "Advisory & Expertise", "Volume of compliance queries handled", "KPI Impact", "Compliance queries"},
				            {"Agent: Compliance & Policy", "Advisory & Expertise", "% of compliance queries resolved autonomously", "Workflow Automation", "% compliance autonomous"},
				
				            {"Agent: General Purpose", "Advisory & Expertise", "Reduction in time: General assistance", "Usage", "Assistance time saved"},
				            {"Agent: General Purpose", "Advisory & Expertise", "Volume of general assistance interactions", "KPI Impact", "Assistance interactions"},
				            {"Agent: General Purpose", "Advisory & Expertise", "% of general queries handled autonomously", "Workflow Automation", "% assistance autonomous"},
				
				            {"Domain-Specific Agent", "Advisory & Expertise", "Reduction in time: Specialist queries", "Usage", "Specialist time saved"},
				            {"Domain-Specific Agent", "Advisory & Expertise", "Volume of specialist queries handled", "KPI Impact", "Specialist queries"},
				            {"Domain-Specific Agent", "Advisory & Expertise", "% of specialist work delegated to agent", "Workflow Automation", "% specialist autonomous"},
				
				            {"Cross-Org Agent", "Advisory & Expertise", "Reduction in time: Cross-organisational coordination", "Usage", "Cross-org time saved"},
				            {"Cross-Org Agent", "Advisory & Expertise", "Volume of cross-org workflows AI-supported", "KPI Impact", "Cross-org workflows"},
				            {"Cross-Org Agent", "Advisory & Expertise", "% of cross-org coordination automated", "Workflow Automation", "% cross-org autonomous"},
				
				            // ============ TECHNICAL CAPABILITY ============
				            {"Code Writing", "Technical Capability", "Reduction in time: Writing code", "Usage", "Code time saved"},
				            {"Code Writing", "Technical Capability", "Volume of code produced with AI", "KPI Impact", "Code produced"},
				            {"Code Writing", "Technical Capability", "% of code produced end-to-end by AI", "Workflow Automation", "% code auto-written"},
				
				            {"Code Analysis", "Technical Capability", "Reduction in time: Code review / analysis", "Usage", "Review time saved"},
				            {"Code Analysis", "Technical Capability", "Volume of code analysed / reviewed", "KPI Impact", "Code reviewed"},
				            {"Code Analysis", "Technical Capability", "% of code review handled autonomously", "Workflow Automation", "% code review autonomous"},
				
				            // ============ GENERAL AI ASSISTANCE ============
				            {"General Q&A", "Advisory & Expertise", "Reduction in time: Ad-hoc questions", "Usage", "Q&A time saved"},
				            {"General Q&A", "Advisory & Expertise", "Volume of general questions answered", "KPI Impact", "Questions answered"},
				            {"General Q&A", "Advisory & Expertise", "% of general queries self-served via AI", "Workflow Automation", "% Q&A self-served"},
				
				            {"M365 Chat Q&A", "Advisory & Expertise", "Reduction in time: M365 chat interactions", "Usage", "M365 chat time saved"},
				            {"M365 Chat Q&A", "Advisory & Expertise", "Volume of M365 Copilot chat queries", "KPI Impact", "M365 chat queries"},
				            {"M365 Chat Q&A", "Advisory & Expertise", "% of queries handled via M365 Copilot chat", "Workflow Automation", "% M365 chat self-served"},
				
				            {"Teams Q&A", "Advisory & Expertise", "Reduction in time: Teams-based questions", "Usage", "Teams chat time saved"},
				            {"Teams Q&A", "Advisory & Expertise", "Volume of Teams chat queries", "KPI Impact", "Teams queries"},
				            {"Teams Q&A", "Advisory & Expertise", "% of Teams queries self-served", "Workflow Automation", "% Teams self-served"},
				
				            {"Browser Q&A", "Advisory & Expertise", "Reduction in time: Browser-based assistance", "Usage", "Browser time saved"},
				            {"Browser Q&A", "Advisory & Expertise", "Volume of browser queries AI-assisted", "KPI Impact", "Browser queries"},
				            {"Browser Q&A", "Advisory & Expertise", "% of browser queries self-served", "Workflow Automation", "% browser self-served"},
				
				            {"General Chat", "Advisory & Expertise", "Reduction in time: General AI chat", "Usage", "Chat time saved"},
				            {"General Chat", "Advisory & Expertise", "Volume of chat interactions", "KPI Impact", "Chat interactions"},
				            {"General Chat", "Advisory & Expertise", "% of chat queries self-served", "Workflow Automation", "% chat self-served"}
				        }
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {
				        {"TaskBehavior", type text},
				        {"WorkArchetype", type text},
				        {"SuccessMetric", type text},
				        {"SuccessMetricClass", type text},
				        {"SuccessMetricShort", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

